### ISSUE TITLE
When migrating an installation from Squirrel.Windows to Velopack, updater should restore pinned taskbar shortcuts

### ISSUE THREAD

**Issue by Trinitek** [velopack/velopack#100]
The current behavior of the updater (0.0.462-gf8acc97) is to scan the desktop, Start menu, and taskbar pins for shortcuts that match a Squirrel app target, delete them, and then recreate shortcuts in the default locations. This does not, however, take into account whether the user has deliberately pinned the shortcut to the taskbar. So, when a migration is performed, the user loses the pin.

This is especially troublesome on my Win11 machine (not sure if the behavior is the same on 10), as the taskbar does not immediately refresh when the shortcut that's backing the taskbar pin is deleted. Clicking the zombie pin then results in a message like the following:

![image](https://github.com/velopack/velopack/assets/6560270/21fd14ca-4fe7-47b7-aa56-52caf7e364dc)

~~The zombie pin will disappear after the computer is rebooted or the Explorer process is otherwise restarted.~~ No it does not, I was mistaken. The icon just reverts to a generic "sheet of paper" graphic on restart.

**Comment by caesay** [comment]
Probably need to run https://learn.microsoft.com/en-us/windows/win32/api/shobjidl/nf-shobjidl-istartmenupinnedlist-removefromlist before deleting any `.lnk` files. Will look into this.
