### ISSUE TITLE
Code signing OSX for macos TFM

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#106]
Xamarin (used automatically if specifying a macos tfm like `net8.0-macos`) stores binaries in the `MonoBundle` folder which is actually not a valid store for binaries, thus codesign does not sign it and the package can not be notarized.

~~Additionally, we should allow notarization without code signing. To enable more advanced signing scenarios, we can allow users to pre-sign their app bundle before packing a velopack release.~~ - This might not be possible due to `UpdateMac` not getting signed.

**Comment by caesay** [comment]
Removing from v1 milestone as there is a workaround (code-sign the MonoBundle folder before giving .app bundle to Velopack)

**Comment by AArnott** [comment]
Consider this issue sponsored:
![image](https://github.com/user-attachments/assets/5a90aafc-7e00-4c3e-9f9e-dfc3bf9c6893)

Thanks!
