### ISSUE TITLE
Net 8 support?

### ISSUE THREAD

**Issue by sam-wheat** [velopack/velopack#107]
Nuget tells me vpk is not compatible with net 8.  Any plan to make that happen?

**Comment by ysmoradi** [comment]
You can download our .NET 8 based open source apps published by velopack from [here](https://github.com/bitfoundation/bitplatform#-oss-showcases)
I didn't face any issue

**Comment by caesay** [comment]
Net 8 is fully supported by Velopack. We ship net8 in our tool (vpk) and also in our app nuget package (Velopack). Keep in mind you can not install `vpk` into your project, you need to install it as a dotnet tool eg. `dotnet tool update -g vpk`. Double check you've installed the right packages and if you are still having issues, please share your error/log here and I should be able to help!
