### ISSUE TITLE
How to specify folder where release artifacts are created?

### ISSUE THREAD

**Issue by sam-wheat** [velopack/velopack#109]
I am in learning/testing mode, trying to create a release and output it to a shared folder on my local disk.

The following are run from a command window opened in the folder where MyApp.csproj lives.

Publish command:

	dotnet publish -c Release --self-contained -r win-x64 -o .\bin\Release\net8\win-x64\publish
	
	
Pack command:

	vpk pack -u MyApp -v 1.0.0 -p .\bin\Release\net8\win-x64\publish -e MyApp.exe -o c:\Shared\Releases\MyApp\Windows\
	

Publish appears to have run ok, however I ran into a problem with pack.  This path, `c:\Shared\Releases\MyApp\Windows\`, is valid and the folder exists.  However when I ran the pack command I got this error:

> [10:51:03 FTL] Command WindowsPackCommand had an exception.   UnauthorizedAccessException: Access to the path 'c:\Shared\Releases\MyApp\Windows\RELEASES' is denied.

It appears all the files in the publish folder were copied to `c:\Shared\Releases\MyApp\Windows\` and no deployment files were created.

I then created a `Releases` folder under `c:\Shared\Releases\MyApp\Windows\` and ran the above `pack` command again.

I got the same error message however this time MyApp.nupkg, .zip, and ..Setup.exe were created in `c:\Shared\Releases\MyApp\Windows\` and the `Releases` folder remains empty.

Desired functionality (unless I'm just doing it completely wrong) is:

App will be published to `.\bin\Release\net8\win-x64\publish`
Release artifacts will be created in `c:\Shared\Releases\MyApp\Windows\`

**Comment by caesay** [comment]
I can't reproduce this. I ran vpk with exactly the command line arguments you provided (and the folder didn't even exist) and Velopack correctly created all of the necessary folders and output the packages there. 

I would guess that there is either a permissions issue or there is another process (eg. notepad.exe?) locking the RELEASES file preventing Velopack from writing to it.

![image](https://github.com/velopack/velopack/assets/1287295/29d38f0c-4763-46f3-a61f-66cc5a86a3b9)

**Comment by sam-wheat** [comment]
Well I am sorry for bothering you.  I rebooted and sure enough it ran fine.
