### ISSUE TITLE
Add Source Link support

### ISSUE THREAD

**Issue by genment** [velopack/velopack#117]
Hi, thanks for creating this amazing tool.

Would you consider adding support for Source Link in the NuGet package?

## Benefits:
1. **Improved Debugging Experience**: Including Source Link allows developers to step into the source code while debugging, providing a more comprehensive understanding of how Velopack works.
2. **Enhanced Navigation**: It facilitates easy navigation to classes and methods directly from the IDE, improving developer productivity and code comprehension.

## References:
- [NuGet Symbol Packages (.snupkg)](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
- [Source Link Guidance](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)

Thanks!

**Comment by caesay** [comment]
Hi, we already support / include source link, are you having an issue using it?

**Comment by genment** [comment]
My IDE is VS 2022 community edition + Jetbrain Resharper

I have installed the latest version `0.0.474-gb9d73fc` from NuGet and added code by following the [quick start for C#](https://docs.velopack.io/getting-started/csharp). When I set a breakpoint at `VelopackApp.Build().Run();` and run the project, the debugger can't step into the `VelopackApp` class. Instead, it skips the breakpoint and goes to the next line of code.

Additionally, when I press `Ctrl + left click` on the `VelopackApp` class name, the IDE does not navigate to the real source code of the `VelopackApp` class. Instead, it shows only the declarations without method bodies.

**Comment by genment** [comment]
Hi, I found the reason for the issue. The symbol package is not uploaded to NuGet. As you can see, the first screenshot shows [Avalonia](https://www.nuget.org/packages/Avalonia/11.1.0-beta2), which provides both the `.nupkg` package and the `.snupkg` symbol package for downloading. The second screenshot shows [Velopack](https://www.nuget.org/packages/Velopack/0.0.474-gb9d73fc), which has only the `.nupkg` package.

Uploading the `.snupkg` symbol package for Velopack should resolve the issue.

![avalonia](https://github.com/velopack/velopack/assets/5207957/90435d99-f934-4443-a25b-3a36f4f6e6a9) ![velopack](https://github.com/velopack/velopack/assets/5207957/6e6d778c-2ac1-4a75-a3ae-d11918e066b2)

**Comment by caesay** [comment]
We do ship symbols embedded in the `.dll` files using the following csproj properties:

```xml
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
```

I'll try splitting the symbols out into a separate package and see if that helps.

**Comment by caesay** [comment]
I believe it's working on the latest pre-releases, but if you have any further please let me know.
