### ISSUE TITLE
Update documentation to reflect differences in file association registration from Squirrel.Windows

### ISSUE THREAD

**Issue by Trinitek** [velopack/velopack#125]
There needs to be a mention in the documentation for this I think. I've got a file association for a Squirrel.Windows app that points to `%localappdata%\MyApp.exe` which is the Squirrel stub executable. This stub does not exist on fresh Velopack installs, so I need to update the associations to point to `current`. I missed this detail and now I've got a confused customer who can't double-click files.

**Comment by caesay** [comment]
I have updated the migration guide with these details https://docs.velopack.io/migrating/squirrel
