### ISSUE TITLE
Linux update failures

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#128]
Report from discord:

![image](https://github.com/velopack/velopack/assets/1287295/553492c4-cfbc-418d-b9a7-2066f5333a6a)

@caesay
hm yes that looks familiar
Well not exactly. so cross-device I've seen before, that happens if we try and rename .AppImage when it was extracted to a different /dev to the target location. But it looks like that was handled ("trying again with a copy"). The copy failed due to "text file busy" which I've not seen before. 
This seems to suggest that it happens when trying to modify a running executable https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix but that doesn't sound right
It's strange because 
the AppImage is not an executable, and
we should be waiting for it to exit before performing the update anyway
does it reproduce or was it a one-off?

@AArnott 
Yes, it happened again on the next app update.
![image](https://github.com/velopack/velopack/assets/1287295/0bace737-118a-43c6-9842-ca0c26f1d8c2)

@caesay 
I've not seen this error before and don't see anything obvious in the code, unless you're able to provide some more details I'll likely need to install xubuntu and try myself at some point.

Without any specific ideas of what is going wrong, here are some shoot-in-dark questions:
Has an update ever worked on this machine, if so, do you have logs for that?
Can you describe your current disk layout eg. using lsblk or df -h?
Is another instance of the application running while you try to update or is it only the instance being updated?
After the update fails can you try manually copying the update into place by extracting the nupkg (path in the logs, it's a zip) and then doing a cp to replace the existing AppImage on the desktop?

@AArnott 
I can repro the exact problem myself with WSL that my user experienced in xubuntu. Here are the answers to your questions from my environment:
No, update has never worked.
lsblk output:
NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0   7:0    0 446.7M  1 loop /mnt/wsl/docker-desktop/cli-tools
loop1   7:1    0 147.5M  1 loop
loop2   7:2    0 717.6M  1 loop
sda     8:0    0   256G  0 disk
sdb     8:16   0 342.4M  1 disk
sdc     8:32   0   256G  0 disk /
sdd     8:48   0   256G  0 disk /mnt/wsl/docker-desktop/docker-desktop-user-distro
sde     8:64   0   256G  0 disk /mnt/wsl/docker-desktop-data/isocache

It's the only instance ever invoked. However, when my app launches, it looks for other processes by the same path and attempts to communicate with them over a unix domain socket and then exits (so I have only one process left running at a time).
Manually copying over works fine.

Interestingly, the failure I saw happened while I ran the AppImage from the /mnt/c/Users/andre/Downloads folder. When I copied the AppImage to /home/andre and ran it from there, update worked. So at least for my case the error seems to be related to the file being under /mnt/c which indeed is a different 'device' than /var/tmp/velopack.

**Comment by caesay** [comment]
Fixed in 0.0.523-g5727de1

**Comment by AArnott** [comment]
Just to circle back, yes this fixed the issue for my beta tester too.
