### ISSUE TITLE
`IsWow64Process2` is not available on older Windows versions

### ISSUE THREAD

**Issue by Trinitek** [velopack/velopack#133]
Version 0.0.523-g5727de1.

Added in commit ac498494bdbd8ba52d9df3e4ad99b63bc7083393

`IsWow64Process2` is not available prior to Win10 1709 (build 16299) according to https://learn.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2. This will cause the installer to fail on older systems.

I have verified this on my Windows 7 VM.

**Comment by caesay** [comment]
What was the failure? It should work fine since we're handling that error. 

[On line 63](https://github.com/velopack/velopack/commit/ac498494bdbd8ba52d9df3e4ad99b63bc7083393#diff-ade10bbf70709263c67fdfe87583b37e6661de82d6c8401f0ab4360d137d37fdR63) we try IsWow64Process2, if that fails, we fall back to [IsWow64Process on line 68](https://github.com/velopack/velopack/commit/ac498494bdbd8ba52d9df3e4ad99b63bc7083393#diff-ade10bbf70709263c67fdfe87583b37e6661de82d6c8401f0ab4360d137d37fdR68), and if _that_ fails we just fall back to the current binary architecture.

**Comment by Trinitek** [comment]
Ghidra reveals that `IsWow64Process2` is statically imported, as is `IsWow64Process` when it wasn't earlier (which is okay), and then there's also an API set `API-MS-WIN-CORE-SYNCH-L1-2-0.DLL` which definitely does not exist on Win7.

Here's the error message:
![image](https://github.com/velopack/velopack/assets/6560270/1ba3621c-d61b-4ef6-bf90-6d128263c4af)

**Comment by caesay** [comment]
I've not really put any effort into testing for win7 thus far - do you still have users there?

**Comment by Trinitek** [comment]
I do. I haven't deployed this version yet though. I'm currently on 0.0.503-gc69e323.

**Comment by ysmoradi** [comment]
> I've not really put any effort into testing for win7 thus far - do you still have users there?
I do as well )":

**Comment by caesay** [comment]
Okay, having done a little reading - it looks like only AppVeyor agents support Windows 7 and only with self-hosted agents. I'll have a look at what it would take to get a Win7 VM going with AppVeyor so we can automate these tests.

**Comment by Trinitek** [comment]
I can't imagine a legitimate way to get a Win7 license in current year other than through a Visual Studio Standard subscription. I had a thought that you could run `dumpbin /imports` and throw a pipeline warning if there's a module or symbol that isn't recognized. You could maintain a short list of modules and functions that are known to work.

**Comment by caesay** [comment]
I have Win7 licenses, so that's not an issue, but it will cost some amount of money to host the VM.

**Comment by Trinitek** [comment]
There's one use of it here that I am slightly confused about: https://github.com/velopack/velopack/blob/298084655b00be6c5c7ed20b2e998fe8b13e7f72/src/Velopack/VelopackRuntimeInfo.cs#L222-L230

This is referenced through a DllImport. If the function doesn't exist, does that try/catch actually work? I thought imports were resolved when the static class is loaded by the runtime.

**Comment by caesay** [comment]
I'm confident that one is fine, although it's easy enough to test yourself, just try `DllImport` -ing a function that doesn't exist, or a dll that doesn't exist.

**Comment by caesay** [comment]
I was not able to automate this in the end. However I have managed to get things building with rust 1.75 (the last official toolchain to support windows 7) and I've also dynamically linked `IsWow64Process2` which appears to be the only missing function in Win7. Everything appears to be working in 0.0.530-g4f25004

**Comment by Trinitek** [comment]
👍 Verified working on win7-x64 non-ESU and win10.0.14393-x86. There is a separate issue I opened for win7 at #138.
