### ISSUE TITLE
WPF project named velopack causes dotnet error when adding package

### ISSUE THREAD

**Issue by JLdgu** [velopack/velopack#135]
This error will likely only occur when making a test/sample project to trial velopack

Steps to reproduce:

create a directory name velopack
```
cd velopack

dotnet new wpf

dotnet add package Velopack
```

result is

![image](https://github.com/velopack/velopack/assets/114992499/e359eedb-1ccf-4d4a-bc07-ab21f1d92191)

**Comment by caesay** [comment]
That looks like a bug in NuGet, or might just be an unsupported configuration (because now you have two projects / dll's that have the same name...)
