### ISSUE TITLE
UpdateNix program under Linux does not support arm64

### ISSUE THREAD

**Issue by zh3305** [velopack/velopack#137]
On arm64 Lunux Failed to execute update

**Comment by caesay** [comment]
Confirmed, we don't currently compile linux arm64 binaries. Given we've just added arm64 for macos I think it makes sense here too. I will have a look.

**Comment by caesay** [comment]
Released in 0.0.541-gf8f3de0 (a8e40defb85d3ae63ad493b2a6eb8739e47f6d64)
