### ISSUE TITLE
Question: How to set up an velopack installer and updater to pull updates and installer from private Azure Storage Blob?

### ISSUE THREAD

**Issue by LiamDHall** [velopack/velopack#139]

**Comment by lmaslovs** [comment]
Hey Liam,
I was solving similar issue today but with Github.

Originally I was setting my download source to this:

`var updateManager = new UpdateManager("https://github.com/username/repo/releases/latest/download");`

This way I couldn't get updates from a private directory.

But then I found this:
https://github.com/velopack/velopack/blob/develop/src/Velopack/Sources/GithubSource.cs

So i changed my implementation to:

```
var source = new GithubSource("https://github.com/lmaslovs/WpfVelopack", token, false);
var updateManager = new UpdateManager(source);
```

This way I can use the authorization token to get releases from private directory.

I don't think they have Azure source implementation, but maybe I missed. Potentially you could implement your own source using IUpdateSource interface. I hope this helps!

**Comment by caesay** [comment]
If you need to implement authenticated download of Azure Blob's you will need to implement a custom `IUpdateSource` as mentioned above. Feel free to use the code from one of the other sources (eg. `SimpleWebSource`) if helpful.

Also, keep in mind that any key/token/etc. you store in your application code will be easily retrievable with a hex editor or dissassembler. So make sure that the credentials you store in your code only have very limited read-only access.
