### ISSUE TITLE
Portable stub.exe is not being signed

### ISSUE THREAD

**Issue by leonidcan** [velopack/velopack#14]
All binaries are signed by my cert but stub.exe in Portable.zip root (Update.exe is also signed)

Also, how can I give a stub different more friendly name than main executable?

**Comment by caesay** [comment]
Thanks for reporting this!

**Comment by caesay** [comment]
Fixed in 04cf01cc87f04904b974dbc4275b1f0ecb97e87d. 
The stub will now respect the `--packTitle` argument, similar to shortcuts in the installed apps.
