### ISSUE TITLE
Migration from Squirrel.Windows - delta package same as full package

### ISSUE THREAD

**Issue by madorjan** [velopack/velopack#149]
Hi,

we currently migrate from Squirrel.Windows to velopack. During testing we found out that the first release after migration has the same  file size for the delta and full package.

Obviously, this is due to the folder structure of the nupkg, which is lib/app/* for velopack and  lib/net45/* for our Squirrel releases.

Is it possible to configure the root folder of velopack, such that deltas are computed correctly in migration scenarios like this (e.g. lib/net45 instead of lib/app)?

**Comment by madorjan** [comment]
Ok, seems to be hardcoded here: https://github.com/velopack/velopack/blob/f70fb82ceed7f6822a73eea3e4ac0478cf39e53a/src/Velopack.Packaging/PackageBuilder.cs#L263

Can it have any side-effects if this path would be made configurable via a commandline argument of `vpk pack`?

**Comment by caesay** [comment]
Delta's between Squirrel and Velopack are not supported - I believe we prevent them from being generated at all in the latest prereleases. Please don't ship a delta for your first Squirel->Velopack release.
