### ISSUE TITLE
Updating on other partition than C: fails

### ISSUE THREAD

**Issue by spechter** [velopack/velopack#15]
Hello there,

I've used Velopack to install my application on a different partition.

In this constellation the update process fails. 

> 06:44:04 [INFO] Starting Velopack Updater (0.0.231)
> 06:44:04 [INFO]     Location: E:\RoboWatch\Update.exe
> 06:44:04 [INFO]     Verbose: false
> 06:44:04 [INFO]     Silent: false
> 06:44:04 [INFO]     Log File: None
> 06:44:04 [INFO] Command: Apply
> 06:44:04 [INFO]     Restart: true
> 06:44:04 [INFO]     Wait: true
> 06:44:04 [INFO]     Package: Some("E:\\RoboWatch\\packages\\RoboWatch-0.1.20-full.nupkg")
> 06:44:04 [INFO]     Exe Args: None
> 06:44:04 [INFO] Loaded manifest for application: RoboWatch
> 06:44:04 [INFO] Root Directory: E:\RoboWatch
> 06:44:04 [INFO] Attempting to open global system mutex: 'velopack-RoboWatch'
> 06:44:04 [INFO] Reading parent process information.
> 06:44:04 [INFO] Waiting 60000ms for parent process (1244) to exit.
> 06:44:04 [INFO] Getting ready to apply package to RoboWatch ver 0.1.19: E:\RoboWatch\packages\RoboWatch-0.1.20-full.nupkg
> 06:44:04 [INFO] Applying package to current: 0.1.20
> 06:44:04 [INFO] Checking application pre-requisites...
> 06:44:04 [INFO] Running --veloapp-obsolete hook...
> 06:44:04 [INFO] Hook executed successfully (took 102.1527ms)
> 06:44:04 [INFO] Checking for running processes in: E:\RoboWatch
> 06:44:04 [WARN] Skipping killing self: E:\RoboWatch\Update.exe (10880)
> 06:44:04 [INFO] Extracting bundle to C:\Users\ME\AppData\Local\Temp\velopack_Qw1n3KqY
> 06:44:04 [INFO] Extracting 1233 app files to current directory...
> 06:44:15 [INFO] Checking for running processes in: E:\RoboWatch
> 06:44:15 [WARN] Skipping killing self: E:\RoboWatch\Update.exe (10880)
> 06:44:15 [INFO] Replacing bundle at E:\RoboWatch\current

I have made sure, that there are no other processes accessing the directory to rule out my problem is a duplicate of #4 .

As far as I understands, this is rooted in the updater using the function `fs::rename` (src/Rust/src/commands/apply_windows_impl.rs:49) which [cannot operate on two seperate partitions](https://stackoverflow.com/a/70947813). 

I can think of two different approaches, copying the updated files instead of renaming them or locating the temporary files inside the target directory. 

Since I don't have any experience in Rust, let alone replacing the velopack package with a fork, I'm afraid I can not offer to implement and test these changes myself.

**Comment by caesay** [comment]
Thanks. I think the fix for this will be extracting the application to a temp directory on the same drive of the final destination (so that the rename can remain really fast and not involve copying/moving files between drives). I'll look at this.

**Comment by caesay** [comment]
Fixed in 65e4b30f9537c29d774d808e46e9f8b27b073453

**Comment by spechter** [comment]
I just gave it a go and it runs as expected.

Thank you for your quick work, it's much appreciated.

**Comment by caesay** [comment]
If you like the project, consider starring it and sharing it!
