### ISSUE TITLE
Add restart capabilities

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#151]
Have had a few requests for a generic "restart" function which is detached from update/apply. 

We have all the code for this already, just need to detangle the `start` command and make it cross-platform. Then expose it through UpdateManager

**Comment by smallketchup82** [comment]
Could the function that implements this have a parameter to toggle sending a SIGKILL vs SIGTERM, or attempt a SIGTERM and only send a SIGKILL after a timeout?

osu!lazer shows a nice exit animation when given a SIGTERM, but exits immediately when given a SIGKILL. A SIGTERM would be more user friendly.

I figured I'd leave this here as a comment on design
