### ISSUE TITLE
Unable to utilize cross compiling on linux

### ISSUE THREAD

**Issue by smallketchup82** [velopack/velopack#153]
It seems like using directives is completely broken for me.

When running
```
vpk win pack -u osulazer -v 2024.630.0 -r win-x64 -o "/home/smallketchup/RiderProjects/osu-deploy/releases" -e "osu\!.exe" --channel=win  --splashImage="/home/smallketchup/RiderProjects/osu/assets\lazer-nuget.png" --icon="/home/smallketchup/RiderProjects/osu/osu.Desktop/lazer.ico"
```
I get the following error:
```
'win' was not matched. Did you mean one of the following?
-i

Unrecognized command or argument 'win'.
Unrecognized command or argument '--splashImage=/home/smallketchup/RiderProjects/osu/assets\lazer-nuget.png'.
At least one of the following options are required '--packDir' and '--appDir'.
```

This occurs on both zsh and bash, using Ubuntu 24.04, .NET 8, and `Velopack CLI 0.0.359` installed globally

I'm not sure if I'm just flat out doing this wrong, but I've read https://docs.velopack.io/packaging/cross-compiling about 5 times now, and have double checked vpk's source code to make sure I'm formatting things correctly, and to me it looks as though I am, so I'm not too sure as to why this is failing.

**Comment by caesay** [comment]
Hi, your syntax is wrong. 

It's not `vpk win pack`

The valid syntax is `vpk [win] pack`

Additionally, cross-compiling is not available in 0.0.359 - please check out the latest pre-release for this feature :)

Sorry for the difficulties.
