### ISSUE TITLE
Rare sporadic PermissionDenied breaking the installation

### ISSUE THREAD

**Issue by Dunge** [velopack/velopack#159]
Hello @caesay

OS: Windows 10/11

I once contacted you on Discord months ago with this same problem, but this is still happening intermittently. I had 3 users who had the same issue recently.

What happen is the application launch, detect and download a new update, then the Updater.exe process launch, extract the file in a tmp folder, and when it tries to copy it to the "current" folder it fails for some reason and pop an error and exit. The "current" folder is at this point deleted and the shortcuts to the app are invalid. The user has then no choice to uninstall and reinstall the application.

![image](https://github.com/velopack/velopack/assets/6548184/3c912e3d-fc76-44ed-94e7-a556cdbd1c68)
"Accès refusé" is french for Access Denied.

Now as you know it's practically impossible the user don't have access to write in his LOCALAPPDATA folder on his local disk, and as you suggested last time it's probably an external process like an anti-virus blocking the operation.

I do not have a recent velopack.log of the error (because it doesn't keep a long history), only the same I collected months ago from an older version, but I guess it's still the same today with the latest. Relevant part:

```
07:10:20 [INFO] Hook executed successfully (took 120.6698ms)
07:10:20 [INFO] Checking for running processes in: C:\Users\username\AppData\Local\appname
07:10:20 [WARN] Skipping killing self: C:\Users\username\AppData\Local\appname\Update.exe (21344)
07:10:20 [INFO] Extracting bundle to C:\Users\username\AppData\Local\appname\packages\tmp_5bCvuG79
07:10:20 [INFO] Extracting 1103 app files...
07:10:22 [INFO] Checking for running processes in: C:\Users\username\AppData\Local\appname
07:10:22 [WARN] Skipping killing self: C:\Users\username\AppData\Local\appname\Update.exe (21344)
07:10:22 [INFO] Replacing bundle at C:\Users\username\AppData\Local\appname\current
07:10:23 [WARN] Retrying operation in 333ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
07:10:23 [WARN] Retrying operation in 666ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
07:10:24 [WARN] Retrying operation in 1000ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
07:10:25 [WARN] Last retry in 1000ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
```

I thought maybe the app would still be running, but I see you scan to kill it twice already, and I also found ticket #4 that has a different message in this situation ("The process cannot access the file because it is being used by another process."). And the fact that the "current" folder is deleted doesn't seem to hint that way.

I asked one user to check for his anti-virus log (they use ESET cloud module) and there is a line saying "Updater.exe was submitted to ESET virus lab for analysis" during that time. Technically that file upload should not be blocking any operation, but it could also be a clue. I don't think "Updater.exe" is the file getting written thought, but the executable that is trying to copy the files in the "current" folder.

My suggestion would be maybe do your retries over a longer period than 1 second?

For your information, I also asked one of this user who just had this happen to him to do this process: "uninstall > re-install (using an old installer) > launch app and let it update". He did it 10x and the error never happened again, proving that this is really sporadic and not related to user permissions. The anti-virus submission process is currently my best bet, but maybe you could have other ideas why this is happening.

**Comment by caesay** [comment]
Depending on how/what is locking the folder, there are a variety of errors that can be thrown. Access denied, Permission denied, The file is in use, you name it. Windows sucks for that. 

I would be willing to extend the retry duration a bit, the trouble is, if there is some non-resolveable issue there, the longer we wait the worse the user experience is. (But I would agree that failing to update when waiting longer would fix it is worse). 

Usually when people report this error it really is user-error. Sometimes it's logging, sometimes it's cmd.exe (like the issue you linked) etc. But in this case based on your anecdotes it seems there is something legitimately wrong here. I just don't know what exactly the issue is. I'll leave this open and do a bit of investigating.

**Comment by caesay** [comment]
Could you tell me, have you had any reports of this issue from non-enterprise non-domain-joined users, or are your users mostly in enterprises with more strict security policies / anti-virus? I've never experienced it myself so just curious.

**Comment by Dunge** [comment]
To be honest we only did one public update months ago and received some problem report but nothing precise enough to trace. I'm just prepping out for our next update to try to reduce to possibility this could happen to public users.

So all the 3 different users I mentioned (one had it happen twice this month) are from internal employees when updating our development version. This dev version receive new updates every 2-3 days, so it works more often than it doesn't. All of these users on on the same enterprise, always domain-joined, and all using the same ESET anti-virus solution. But as far as struct security policies, no, not really. I had a meeting with the IT guy handling the domain and we couldn't find anything specific that would cause permission denied errors. His suggestion was "try doing retries", which is what I noticed you are already doing, just not over a long period.

**Comment by caesay** [comment]
I moved the copy logic out of Rust and use system commands like `mv` on UNIX. Reason being the rust commands are simpler whereas the built-ins are more robust and can handle a wider variety of system configurations. I'm wondering if doing something with `robocopy` on windows (rather than `fs::copy` / `fs::rename`) would be prudent here. Robocopy would be slower than a simple `fs::rename` but would be more robust (because it doesn't require the folder to be renamed first), and it has built-in retry logic.

**Comment by Dunge** [comment]
Interesting. Unfortunately I can't say I have knowledge about robocopy, never heard of it before :). fs::copy is the Rust method to copy files I assume? Do you know if internally it uses the WIN32 API (CopyFile function (winbase.h)) which should be the most "normal" way for a software to do it? Otherwise there's also posibility to use command prompt "cp" calls, or PowerShell Copy-Item, but that seems weird.

**Comment by caesay** [comment]
I have written some new windows update logic which will use the try the `fs::rename` first, and if that fails, will use robocopy instead which is slower but is far more resilient and can perform updates properly even if certain processes are locking the current directory.

**Comment by Dunge** [comment]
Amazing I've rarely seen a GitHub project where the owner is as proactive as you are :)

Let's hope that will solve the issue!

Quick logistics question, when we pack a new release with the latest velopack/vpk nugets, is the updater.exe used in that update process the one of the previous release that was installed at that time or the newest one? (ie. Does it takes two updates to apply the changes).

**Comment by caesay** [comment]
`updateManager.DownloadUpdates()` is what replaces `Update.exe`. 

>Amazing I've rarely seen a GitHub project where the owner is as proactive as you are :)

Thanks! Of course it's not needed, but if you'd like to support the project and contribute to it's future success, consider sharing a testimonial on Discord for our website or sponsoring the project ;)

**Comment by Dunge** [comment]
Unfortunately I got to report this error still happened with both the nuget and vpk updated to `0.0.561-g1e760b4` (updated with pre-release option).

 ```
[update:13204] [15:15:21] [INFO] Replacing current dir with C:\Users\username\AppData\Local\appname\packages\tmp_muw4GnwmrdzzOpLy
[update:13204] [15:15:23] [ERROR] Error applying package: Accès refusé. (os error 5)
[update:13204] [15:15:23] [ERROR] Apply error: Unable to find executable to start: 'C:\Users\username\AppData\Local\appname\current\appname.exe'
 ```

Weirdly I don't see the traces for the 3 retries anymore, just a single line with a straight permission denied

**Comment by caesay** [comment]
That log doesn't look correct. Can you please send me the rest of it the log for this run?

**Comment by Dunge** [comment]
Sent on discord
