### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by simader** [velopack/velopack#174]
1. Thanks for the great job. 
2. How can I find out the version number of the Release? 

Previously, in clowd.squirrel, I just parsed the Version from the Directory Name?

`var assembly = Assembly.GetEntryAssembly();
if (assembly?.Location != null)
{
    var directoryName = Path.GetFileName(Path.GetDirectoryName(assembly.Location));
    if (directoryName != null && directoryName.Contains("app-"))
    {
        _version = directoryName.Replace("app-", string.Empty);
        return _version;
    }
}`

**Comment by caesay** [comment]
[UpdateManager.CurrentVersion](https://docs.velopack.io/reference/cs/Velopack/UpdateManager/properties/CurrentVersion)
