### ISSUE TITLE
I have a custom installation issue

### ISSUE THREAD

**Issue by Xncodet** [velopack/velopack#177]
Hello,

If I want to implement a custom installation interface for users to choose installation locations, customize installation progress, and customize update prompts. How do I need to achieve it?

Before this, I used Clowd The Squirrel project source code added my custom interface in the update project, which can only function normally in debug mode. No matter how it is modified and packaged, there will be problems.

So how can this project achieve custom installation and updates? Just implement Windows OS and use WPF to create custom interfaces.

Thank you very much for your answer

**Comment by caesay** [comment]
There's no built in support for custom install/setup stuff. But you can build your own installer if you want. `vpk pack` produces a portable self-updating zip. You can extract the zip, and re-bundle it with the installer of your choice (eg. nsis or wix). 

For updates, there is no UI provided by Velopack. You will need to implement the update UI yourself (so can show it with WPF or whatever you want).
