### ISSUE TITLE
post-install script for windows app

### ISSUE THREAD

**Issue by dationguyen** [velopack/velopack#184]
Hi Guys,
How can I add a post-install script to my package? I want to edit some registry for my app but so far it hasn't been mentioned in any document

Thanks!

**Comment by caesay** [comment]
Docs: https://docs.velopack.io/integrating/hooks

- After Install: https://docs.velopack.io/reference/cs/Velopack/VelopackApp/methods/WithAfterInstallFastCallback
- Before Uninstall: https://docs.velopack.io/reference/cs/Velopack/VelopackApp/methods/WithBeforeUninstallFastCallback

**Comment by dationguyen** [comment]
thanks @caesay !! 

example for those who may need
```c#
VelopackApp.Build().WithAfterInstallFastCallback((v) =>
{
    // do whatever u need here 
    ....
})
.Run();
```
