### ISSUE TITLE
OSX - User friendly app name

### ISSUE THREAD

**Issue by enisn** [velopack/velopack#186]
Documentation says `--packTitle` will be the application name, but when installed by using `.pkg` file, `.app` file name will be same with `-u` parameter. And it doesn't **allow spaces** in it since it generated nuget packages. 

Is it a bug or expected behavior? In the windows, it uses `--packTitle` as application name.

How can I use space in the .app file that is shown in the taskbar?

**Comment by caesay** [comment]
Pack title on macos is set to CFBundleName in the Info.plist rather than the file name, typically Velopack does not produce any files with spaces. My understanding is that this is the documented way to set the "friendly name" of the bundle. There is also CFBundleDisplayName, but my understanding that this shouldn't be set unless the app is localized so Velopack does not set this.

**Comment by enisn** [comment]
Thanks for your advice, the tool before I use was generating `My App Name.app` with spaces and it seems good in the dock, but when I visited the Apple documentation, I saw `LSHasLocalizedDisplayName` should be used to localize app name in the dock & menu. I'll try thanks

**Comment by caesay** [comment]
Can you clarify if there are any changes you think should be made to Velopack here? Is the CFBundleName not appearing in the dock unless LSHasLocalizedDisplayName is set? would you expect Velopack to set this?

**Comment by enisn** [comment]
> Can you clarify if there are any changes you think should be made to Velopack here? Is the CFBundleName not appearing in the dock unless LSHasLocalizedDisplayName is set? would you expect Velopack to set this?

Unfortunately, MacOS doesn't show the `LSHasLocalizedDisplayName` unless adding localization files. When we put a direct string value for this parameter, nothing happened and it showed .app filename still.
