### ISSUE TITLE
Correct url for GitHub releases?

### ISSUE THREAD

**Issue by sam-wheat** [velopack/velopack#187]
var mgr = new UpdateManager("https://github.com/mycompany/myrepo");
    UpdateInfo? newVersion = await mgr.CheckForUpdatesAsync(); // 404 error

What is the correct url for github to check for new releases?  I've used the  url as shown above and also ".../releases" however I only get 404.

**Comment by caesay** [comment]
You need to create a new GithubSource.

Eg. `new UpdateManager(new GithubSource(...));`
