### ISSUE TITLE
Add support for embeding a glibc dependency in .AppImage

### ISSUE THREAD

**Issue by AArnott** [velopack/velopack#189]
My velopack AppImage fails on Debian 12 with:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found 
I don't think this is a velopack bug, but as it is allegedly possible to include glibc in an AppImage, I'm looking for a way to include it in the velopack-created one. The docs.velopack.io don't mention how.
Relevant discussion and proposed solution is to pack glibc:
https://discourse.appimage.org/t/specify-required-glibc-version-in-appimage/2413/5
https://github.com/AppImageCrafters/appimage-builder
But as velopack creates the appimage and not me, I'm not sure how to apply the suggestion.

**Comment by AArnott** [comment]
Discord discussion on the topic: https://discord.com/channels/767856501477343282/1262930722046607451

**Comment by caesay** [comment]
The current suggestion is to use something like https://github.com/natanael-b/make-portable to create an AppDir with your dependencies pre-bundled. You can check this directory of dependencies (without your compiled app) into your source control, and `dotnet publish` your app into it during CI builds.
