### ISSUE TITLE
Suddenly Not Uploading New Release to GitHub.  Happening to multiple repos

### ISSUE THREAD

**Issue by LiamDHall** [velopack/velopack#192]
When trying to upload the new release to GitHub it is suddenly failing. Happening for multiple repos because of the same error
![Error Image](https://github.com/user-attachments/assets/edb27a10-c65e-4b77-b60d-f6a126008a39)

vpk upload github --repoUrl "${{ env.RepoURL }}" --token "${{ env.GH_TOKEN }}" --publish --releaseName "${{ env.Assembly_Name_Or_Title }} ${{ steps.update_version.outputs.VERSION }}" --tag v${{ steps.update_version.outputs.VERSION }} --channel "${{ steps.set_release_channel.outputs.RELEASECHANNEL }}"

**Comment by caesay** [comment]
Fixed in https://github.com/velopack/velopack/releases/tag/0.0.583
