### ISSUE TITLE
Issue with Application Not Restarting Properly After Update

### ISSUE THREAD

**Issue by koojunho** [velopack/velopack#195]
Hello,

I have been experimenting with Velopack for a simple WinForms application. Below is the code I have implemented:
```csharp
[STAThread]
static void Main(string[] args)
{
    FileLog.Log("Main");

    int i = 0;
    foreach (var arg in args)
    {
        FileLog.Log($"args[{i}] {arg}");
        i++;
    }

    VelopackApp.Build().Run();

    FileLog.Log("Did - VelopackApp.Build().Run()");

    ApplicationConfiguration.Initialize();
    Application.Run(new Form1());
}

private static async Task UpdateMyApp()
{
    var mgr = new UpdateManager("http://<my server>/releases");

    var newVersion = await mgr.CheckForUpdatesAsync();
    if (newVersion == null)
        return;

    FileLog.Log("New Version!!");

    await mgr.DownloadUpdatesAsync(newVersion);

    mgr.ApplyUpdatesAndRestart(newVersion);
}
```

Here is the log output I received:
```
[2024-08-04 18:27:00.302] (2.0.26) Main
[2024-08-04 18:27:01.396] (2.0.26) Did - VelopackApp.Build().Run()
[2024-08-04 18:27:02.068] (2.0.26) New Version!!
[2024-08-04 18:27:12.983] (2.0.26) Main
[2024-08-04 18:27:13.001] (2.0.26) args[0] --veloapp-obsolete
[2024-08-04 18:27:13.002] (2.0.26) args[1] 2.0.26
[2024-08-04 18:27:16.281] (2.0.27) Main
[2024-08-04 18:27:16.306] (2.0.27) args[0] --veloapp-updated
[2024-08-04 18:27:16.307] (2.0.27) args[1] 2.0.27
```

I expected the application to restart and display the form after updating to version 2.0.27, but nothing happens. Based on the logs, it seems the message `Did - VelopackApp.Build().Run()` should appear, but it doesn't.

Is this the intended behavior? If so, how can I ensure that the application continues to run without terminating?

Thank you for your assistance.

**Comment by caesay** [comment]
Where are the Velopack logs? There should be logs produced by `UpdateManager` and also Velopack.Log by `Update.exe`. Also what version of the Velopack NuGet are you using? What version of vpk are you using? Please make sure that Velopack and vpk are using the same version.

**Comment by caesay** [comment]
https://docs.velopack.io/troubleshooting/debugging

**Comment by koojunho** [comment]
Thank you for your help. Updating the vpk to the latest version resolved the issue. I appreciate your guidance.
