### ISSUE TITLE
Access is denied error during updates deleting software

### ISSUE THREAD

**Issue by marinapalese** [velopack/velopack#198]
I recently migrated a project to .NET8.0 and decided to replace our installer/updater at the same time. Our updater did not have file diffing and was clunky to work with. It essentially worked by posting the relevant files to deploy in a zip file on our server, and then an updater executable would run each time the program was opened and apply them before opening the program if an update was available.

As a fan of Squirrel, I decided to give Velopack a try as a replacement. However, as I do my slow rollout by uninstalling the program and reinstalling it I'm finding a big issue where sometimes an update will run into an error, and this results in the current folder being deleted and the software effectively gone. The only solution is to go over and reinstall it for the user. The update files are stored on our file server and may be accessed by multiple people at once. In the last update I did I had to help four users reinstall the application. This is a snippet from the log file from one of the users:

14:31:22 [INFO] Getting ready to apply package to Alicat.FlowVision.Production ver 2.0.11: C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production\packages\Alicat.FlowVision.Production-2.0.12-full.nupkg
14:31:22 [INFO] Applying package to current: 2.0.12
14:31:22 [INFO] Checking application pre-requisites...
14:31:22 [INFO] Running --veloapp-obsolete hook...
14:31:23 [INFO] Hook executed successfully (took 921.4237ms)
14:31:23 [INFO] Checking for running processes in: C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production
14:31:23 [WARN] Skipping killing self: C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production\Update.exe (9792)
14:31:23 [INFO] Extracting bundle to C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production\packages\tmp_Hxcg2jCL
14:31:23 [INFO] Extracting 912 app files...
14:31:59 [INFO] Checking for running processes in: C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production
14:31:59 [WARN] Skipping killing self: C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production\Update.exe (9792)
14:31:59 [INFO] Replacing bundle at C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production\current
14:32:02 [WARN] Retrying operation in 333ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
14:32:03 [WARN] Retrying operation in 666ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
14:32:04 [WARN] Retrying operation in 1000ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
14:32:05 [WARN] Last retry in 1000ms... (error was: Some(Os { code: 5, kind: PermissionDenied, message: "Access is denied." }))
14:33:23 [INFO] Package version 2.0.12 applied successfully.
14:33:23 [ERROR] Apply error: Unable to find executable to start: 'C:\Users\Angel.Guillen\AppData\Local\Alicat.FlowVision.Production\current\FlowVision - Production.exe'

This user indicated that they started the update right when prompted, which would run the ApplyUpdatesAndRestart() method, though to my understanding this hasn't been the case for all users. I couldn't a record of anyone else having this issue, so any insight is appreciated.

**Comment by caesay** [comment]
You have cut out the beginning of the logs which displays the current Velopack version, but note that we have fixed bugs related to this issue in 0.0.582. Please update both your Velopack NuGet package and VPK to 0.0.583 or later if you are not already.

**Comment by marinapalese** [comment]
Hi Caesay, my apologies, the version is 0.0.359. I will update to 0.0.583. Just to confirm, I will not need to reinstall the software, correct? Also want to just double check there was nothing that I did wrong.

**Comment by caesay** [comment]
You don't need to re-install anything, just update Velopack nuget and VPK, and make a new release.
