### ISSUE TITLE
Update from the setup (.exe) is deleting the settings files and folders.

### ISSUE THREAD

**Issue by gulshan-verma** [velopack/velopack#201]
### OS

Windows 11

### Programming Language

C#

### VPK Version

0.0.583

### Library Version

v0.0.583

### What happened?

The issue arises when a user with an older version runs a setup executable with the latest updates. Upon running the executable, a popup appears prompting the user to either update the app or cancel the operation. If the user chooses to update, the process behaves like a fresh installation, removing any settings outside of the **current** folder. Is this the expected behavior, as typical updates usually preserve existing settings?

**Comment by caesay** [comment]
Running the installer will completely wipe out the `%localappdata%/{yourapp}` folder. It's a re-install/repair, it's not an update. There is some guidance here https://docs.velopack.io/integrating/preserved-files

**Comment by gulshan-verma** [comment]
> Running the installer will completely wipe out the `%localappdata%/{yourapp}` folder. It's a re-install/repair, it's not an update. There is some guidance here https://docs.velopack.io/integrating/preserved-files

Thanks for the updates.
