### ISSUE TITLE
Updating the updater process

### ISSUE THREAD

**Issue by yaniv5678** [velopack/velopack#206]
* Does velopack support updating the update.exe process itself?
* Can you document what is the purpose of update, stub and install binary crates? (In rust version)
* Which of them are used in windows and which or macOS / Linux?

Thanks!

**Comment by caesay** [comment]
> Does velopack support updating the update.exe process itself?
Yes, update.exe is updated along with your app each time you publish an update

> Can you document what is the purpose of update, stub and install binary crates? (In rust version)
- Update is for updating your app (cross platform), eg. installing new .nupkg updates
- Setup is for installing your app on Windows
- Stub is only included in portable apps on Windows, it provides a nice shortcut for users to click on to run your app
Also see https://docs.velopack.io/reference/cli

> Which of them are used in windows and which or macOS / Linux?
See above
