### ISSUE TITLE
OSX libicuuc.74.dylib not found

### ISSUE THREAD

**Issue by matthewcrews** [velopack/velopack#210]
### OS

OS X Sonoma

### Programming Language

C/C++

### VPK Version

vpk 0.0.594

### Library Version

C++ 0.0.594

### What happened?

When the application is installed on another Mac (OS X Sonoma), it crashes with the following error report:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libicuuc.74.dylib
Referenced from: <B8A080B4-2506-328E-B01C-C5427D9AE7A0> /Applications/ChiAhaExpress.app/Contents/MacOS/ChiAhaExpress.exe
Reason: tried: 
'/opt/homebrew/*/libicuuc.74.dylib' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libicuuc.74.dylib' (no such file),
'/opt/homebrew/*/libicuuc.74.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/73.2/lib/libicuuc.74.dylib' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/icu4c/73.2/lib/libicuuc.74.dylib' (no such file),
'/opt/homebrew/Cellar/icu4c/73.2/lib/libicuuc.74.dylib' (no such file)
(terminated at launch; ignore backtrace
```

It's not finding the ICU 74 library. The `.dylib` files are in the working directory of the application.

When the application is installed on the machine it was built on, it works just fine.

**Comment by caesay** [comment]
Is this issue coming from vfusion binary or from your application?

**Comment by matthewcrews** [comment]
From the application itself. When it is installed of the dev machine that built it, the installed app works. When the app is installed on another users Mac, it crashes. The code is code signed as well.

**Comment by caesay** [comment]
I'm afraid I don't have any suggestions right now. I'm not a MacOS or a C++ developer :) I don't even know how / with what tools and settings you've compiled your application. I gather from the error that your app at runtime is looking for ICU at some hard-coded path that existed on your development machine. I imagine there's some combination of compiler arguments which will tell your compiled app to look for a dylib at a relative path in your app bundle.

**Comment by caesay** [comment]
This should be fixed by the new C++ library
