### ISSUE TITLE
Update Fails File Size Check Sporadically

### ISSUE THREAD

**Issue by Logikgate** [velopack/velopack#222]
### OS

Microsoft Windows [Version 10.0.22000.2538]

### Programming Language

.net 4.8

### VPK Version

0.0.594

### Library Version

Nuget 0.0.594

### What happened?

I packaged an update to my app via `vpk pack` and then used `vpk upload s3` to upload it to an s3 bucket. When the UpdateManager downloads the update and then tries to verify the update it fails and says the file sizes are different.  This happens sporadically, sometimes if I release another update with just a version number change the new update will work, sometimes it also fails a the file size check.

If I download the .nupkg file manually and check the size it is correct. The log output provided shows that it was checking to see if the file was 10874541 bytes and this screenshot from a manual download of the same file shows that it is indeed that size.  A manual check of the sha256 checksum of the manually downloaded file also confirms it is the correct file.

<img width="362" alt="Screenshot 2024-09-09 at 10 59 13 PM" src="https://github.com/user-attachments/assets/d77ddd5c-ae40-4986-8fe1-f055076da074">

### Relevant log output

```shell
Velopack.Compression.ChecksumFailedException: Size doesn't match (10876671 != 10874541). (C:\Users\<USERNAME>\AppData\Local\<APPNAME>\packages\<APPNAME>-3.4.5-full.nupkg.partial)
   at Velopack.UpdateManager.VerifyPackageChecksum(VelopackAsset release, String filePathOverride)
   at Velopack.UpdateManager.<DownloadUpdatesAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Velopack.UpdateManager.<DownloadUpdatesAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Velopack.UpdateManager.DownloadUpdates(UpdateInfo updates, Action`1 progress, Boolean ignoreDeltas)
   at <APP>.TryToDownloadUpdate(UpdateManager mgr, String updateUri)
```

**Comment by caesay** [comment]
I can't be 100% sure, but I doubt this is a bug in Velopack given what you've shared so far. 

We compare `FileInfo.Length` of the downloaded file to the length in the releases.json - and you seem to be agreeing that the size in the releases.json is correct. You can see in the exception message that Velopack was looking for the correct size 10874541 but that the file on disk was larger at 10876671. I highly doubt FileInfo.Length would be reporting the wrong size, so by process of elimination, the file on disk (as downloaded by Velopack) was actually not the correct size. 

Where/what service are you downloading updates from? If you are self hosting a web server, what software? What IUpdateSource are you using? How intermittent is the issue - will it work the next time you check for/download updates or will it continue to fail until you publish a new release?

**Comment by caesay** [comment]
Just re-reading your report - once you've uploaded a release (eg. v1.2.3) you're saying downloading from S3 will always fail the size check, and the issue will not go away until you've released a new version, is that correct? If so, can you please share a URL to a bucket which is currently exhibiting this issue? I can have a look and try and reproduce it.

**Comment by Logikgate** [comment]
Hi Casey,  sorry for the delay, work got in the way. Today I deleted everything in that s3 bucket and have released a few versions to try to give you a clean bucket to debug from that was experiencing this and the problem is gone.

I'm going to close this ticket for now but will reopen if I can reproduce consistently again
