### ISSUE TITLE
.NET 9 RC 1 --framework issue

### ISSUE THREAD

**Issue by ysmoradi** [velopack/velopack#229]
I upgraded WPF app that was working fine with .NET 8 and velopack, to .NET 9 RC 1.
The app is still working fine, but every time I run its installer, it tries to install `net9.0.0-x86-desktop` again!
It seems it can't detect that .NET desktop runtime is already installed.

[Sample apps](https://github.com/bitfoundation/bitplatform/tree/develop?tab=readme-ov-file#-oss-showcases)

**Comment by caesay** [comment]
Velopack supports every released version of dotnet, but 9.0 has not yet been released and we do not support RC versions. If you need support for RC versions of dotnet we would need to further support parsing that in the --framework arg. Eg `--framework net9.0-rc.1-x86-desktop`. 

I don't have specific plans to add support for this in the near future, but you're welcome to send a PR. In the meantime you can also ship your app self contained without the framework arg.
