### ISSUE TITLE
Pass first-run arguments via Setup.exe

### ISSUE THREAD

**Issue by WTGLouisZhou** [velopack/velopack#23]
I have to pass the args to my client app to start. But when I click the setup.exe, it seems that it would run my app automatically. 
Is there any way I can pass my args to setup and then to my app?

**Comment by caesay** [comment]
What kind of arguments?

I could add a parameter to Setup.exe which passes args to the program when it's first launched.

Please be aware that Velopack will run your app during install and updates with special parameters that are handled by VelopackApp.Build().Run(). So for example, your app might get run with '--veloapp-install' and then exit immediately.

The arguments passed in to Setup.exe would not be provided during these initial stages where hooks are being run. They would only be provided when your app is started for the first time after install has been completed.

Also, please note that you can use the --silent flag to Setup.exe to disable the first-run-after-install behavior.. so if you wanted to install it (without running it) you could do that, and then start the app yourself with whatever parameters you like.

**Comment by caesay** [comment]
I'm waiting for some more information about your use-case, if you still need this please let me know.

**Comment by WTGLouisZhou** [comment]
Using silent installation is a good way, Thanks!

**Comment by caesay** [comment]
Had another request for this on Discord so re-opening for consideration
