### ISSUE TITLE
Add WPF sample with .NET8

### ISSUE THREAD

**Issue by Exc1t4r** [velopack/velopack#230]
Hi, please include documentation how to setup C# / WPF .NET8 app. Adding Main() to the Program.cs gives error on InitializeComponent(). Not sure how to fix it.

**Comment by Exc1t4r** [comment]
Currently I'm initialising in App.xaml.cs. Works, but not sure if it's a good place:
`    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            VelopackApp.Build().Run();
            _ = Update();

            var bootstrapper = new Bootstrapper();

            var mainViewModel = bootstrapper.Container.Resolve<MainViewModel>();

            var mainWindow = new MainWindow(mainViewModel);

            mainWindow.Show();
        }
}`

**Comment by caesay** [comment]
There is a WPF sample already, and the Readme there explains how to get things working. What you've done is also fine but it will be slower.

**Comment by Exc1t4r** [comment]
Sample and instructions is for the old .NET framework 4.8. Problem is for the new one .NET8.0, because it is not working if you follow instructions in readme.

**Comment by caesay** [comment]
Simply changing the sample csproj from:

```cs
<TargetFramework>net48</TargetFramework>
```

to:

```cs
<TargetFramework>net8.0-windows</TargetFramework>
```

compiles and works just fine. Please be sure you follow the instructions, including adding `<StartupObject>` to your csproj.
