### ISSUE TITLE
Custom update window

### ISSUE THREAD

**Issue by Chuprinenko** [velopack/velopack#250]
Hi, is there a possibility to customize the update window?
I want to show my own window and display the update process there.

Thanks

**Comment by caesay** [comment]
When checking for updates, or downloading updates, this happens while your app is running. Using the velopack library (eg. nuget) you can integrate this with your existing UI or build whatever custom UI you want. 

The progress bar you see while updates are being applied is shown by Update.exe when your process is closed. It is not possible to customise this UI at all unless you compile VPK yourself and write your UI in Rust. This is not an officially supported configuration.
