### ISSUE TITLE
Updating after exiting app

### ISSUE THREAD

**Issue by khopcuseti** [velopack/velopack#26]
The previous version before the last update was updating my app after a user had logged in and then asking if the user would like to update. On v.0.0.292 the updater doesn't start until a user exits the application. Also, the UpdateManager.ApplyUpdatesAndRestart is marked obsolete in the latest version. I am not sure if this has anything to do with it.

Thanks

**Comment by caesay** [comment]
Hi, the `ApplyUpdatesAndRestart` method will trigger Update.exe. and then call Environment.Exit(0);

![image](https://github.com/velopack/velopack/assets/1287295/fa794e04-ef4e-4053-8abe-083412914ece)

Once your app has exited, then Update.exe will apply the update. Can you please provide some more information?

**Comment by khopcuseti** [comment]
Thanks for the explanation. I think I have it sorted out now. Another function was apparently holding up the method from being called.
