### ISSUE TITLE
dotnet bootstrapping types aspnetcore and runtime results in 404 during installation

### ISSUE THREAD

**Issue by Nidolai** [velopack/velopack#27]
When providing `net8.0-x64-aspnetcore` or `net8.0-x64-runtime` to the `--framework` argument, the installer fails with a "Setup Error" as seen below.
![image](https://github.com/velopack/velopack/assets/11526011/9a4e3ac2-7dbd-4e44-8fa5-6ec5dd7cb5ac)

aspnetcore logs:
```
16:04:02 [INFO] Checking application pre-requisites...
16:04:02 [INFO]     .NET 8.0.2 X64 AspNetCore is missing.
16:04:04 [INFO] Downloading 1 missing pre-requisites...
16:04:04 [ERROR] An error has occurred: https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/8.0/latest.version: status code 404
```

**Comment by caesay** [comment]
Thanks for the report! Just fixed in https://github.com/velopack/velopack/commit/e726bb7251d80e489d6b81df6ea35a0fc9179b3f and will be released shortly.
