### ISSUE TITLE
Add Sdk to the list of allowed DotnetRuntimeTypes

### ISSUE THREAD

**Issue by rzamponiAtIgt** [velopack/velopack#299]
For development tools it's sometimes required that not only Runtime/WindowsDesktop is installed but also the full dotnet SDK. Therefore it would be great if I could simply define **net8-x64-sdk** as runtime requirement. 

If you are of the opinion that this should not be part of the framework setting (to identify the targeted DotnetRuntimeType) it could also be an additional boolean flag to install the full Dotnet SDK instead of only the runtime.

**Comment by caesay** [comment]
Closed by https://github.com/velopack/velopack/pull/434
