### ISSUE TITLE
C++ library doesn't compile with mingw

### ISSUE THREAD

**Issue by fire** [velopack/velopack#300]
### OS

Windows 10

### Programming Language

c++

### VPK Version

None

### Library Version

https://github.com/velopack/velopack/commit/04dd272be2c95aa925f9a3fc83a5456fc4752e0f

### What happened?

When trying to compile rust, the c++ libc fails to work with cross compiling

1. `scoop bucket add dorado https://github.com/chawyehsu/dorado`
1. `scoop install llvm-mingw`
1. `cd src/lib-cpp`
2. `scoop install rustup-gnu`
3. `cargo build`
4. error: failed to run custom build command for `link-cplusplus v1.0.9`

### Relevant log output

Snip. See the later log.

**Comment by fire** [comment]
I linked the wrong log.

**Comment by caesay** [comment]
Hi there, you shouldn't need to compile the rust lib, there are pre-compiled binaries available on Github Releases (just download `velopack_libc_{version}.zip`. Did that not work for you?

**Comment by fire** [comment]
No, because I cannot verify the builds of those pre-compiled binaries

[cargo build.txt](https://github.com/user-attachments/files/17478902/cargo.build.txt)

**Comment by caesay** [comment]
I've not tested trying to compile with gcc / mingw. You're free to review the CI scripts which build, and upload the artifacts here, but if you still can not trust them - maybe try compiling with MSVC (which is the recommended toolchain for Rust on Windows). 

If you're determined to get things building with mingw I guess you may need to figure out where the missing libraires are and install or add them to linker options. 

If you do get things building with mingw and let me know how you managed it, I'd be happy to add that to the docs

**Comment by fire** [comment]
See also https://github.com/velopack/velopack/issues/301

**Comment by caesay** [comment]
Fixed in https://github.com/velopack/velopack/releases/tag/0.0.942
