### ISSUE TITLE
Ship a pre-compiled static library for C / C++

### ISSUE THREAD

**Issue by fire** [velopack/velopack#301]
**Is your feature request related to a problem? Please describe.**

I want to ship a Godot Engine monolithic build with a single executable.

**Describe the solution you'd like**

Embed velopack as a static library inside of the Godot Engine executable

**Describe alternatives you've considered**

Use https://github.com/folbricht/desync and hack an upgrade system out of it.

**Additional context**

**Comment by caesay** [comment]
If you are compiling yourself like you mentioned in #300 (probably with MSVC) then you can change the crate output type from `dylib` to `staticlib` and achieve this.

Are you requesting that Velopack ships pre-compiled static libs?

**Comment by fire** [comment]
> requesting that Velopack ships pre-compiled static libs

For the sake of separating the different issues. Let's say yes to shipping pre-compiled static libs.

**Comment by caesay** [comment]
Fixed in https://github.com/velopack/velopack/releases/tag/0.0.942
