### ISSUE TITLE
Support for `X-AppImage-Version`

### ISSUE THREAD

**Issue by ravener** [velopack/velopack#304]
**Is your feature request related to a problem? Please describe.**

Some tools on Linux such as AppImageLauncher looks for the field `X-AppImage-Version` in the `.desktop` file for desktop integration and then adds them as a menu entry with the format `appname (version)` but if `X-AppImage-Version` is missing it will lead to `appname (1)` a hardcoded version of 1. Major Linux apps like KDE applications that offer an appimage do specify this field correctly.

**Describe the solution you'd like**

There must be a way for app developers to communicate their version information, the `appimagetool` for example supports the `VERSION` environment variable and automatically adds this field to the `.desktop` ([View code](https://github.com/AppImage/AppImageKit/blob/701b711f42250584b65a88f6427006b1d160164d/src/appimagetool.c#L790))

**Comment by caesay** [comment]
Since Velopack already has your app version, presumably we don't need to add any extra cli variables etc, and the following would be fine?

```
[Desktop Entry]
Type=Application
X-AppImage-Version={vpk pack version}
// ...
```

**Comment by ravener** [comment]
> Since Velopack already has your app version, presumably we don't need to add any extra cli parameters etc, and the following would be fine?
> 
> ```
> [Desktop Entry]
> Type=Application
> X-AppImage-Version={vpk pack version}
> // ...
> ```

Yep, that should get the job done, now it's up to how you edit the file, a simple concatenation should be safe I hope, but if you want to rely on an external program I'd like to let you know of [desktop-file-edit](https://man.archlinux.org/man/desktop-file-edit.1.en) which would also do validation, although it seems to fail validation on .desktop files with `Version=1.5` of the spec, at least the tools I have on Debian, just a note but you may know better ways.
