### ISSUE TITLE
When switching Channels, does the current/beta files directories will be preserved?

### ISSUE THREAD

**Issue by ALIENQuake** [velopack/velopack#315]
Imagine the following scenario:

- The app has two channels: stable (version 1.0.0) and beta (version 2.0.0), with `AllowVersionDowngrade = true`.
- The user installs stable 1.0.0, then opts into the beta channel via settings.
- UpdateManager installs beta 2.0.0.

At this point, is the "stable" folder retained on the disk? If the user switches back to the stable channel, will the update manager prevent re-downloading files by using the existing files from "stable" folder?

**Comment by caesay** [comment]
To switch channels Velopack will always download the next full package. Switching channels and preserving local files is currently not possible.

**Comment by caesay** [comment]
I am going to address this with #63
