### ISSUE TITLE
Support Machine-Wide installer by default

### ISSUE THREAD

**Issue by craftbyte** [velopack/velopack#32]
It would be great if a developer could specify an app to be Machine-Installed instead of User-Installed by default. We are deploying our apps into AD environments where users constantly switch computers they use and having to reinstall the app on each computer, due to it installing into AppData/Local in becoming a pain point.

Something like what Squirrel did would be awesome: https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/machine-wide-installs.md

**Comment by caesay** [comment]
The Squirrel machine-wide msi is a huge hack, and I won't be adding something like it. The Squirrel MSI actually installs your app once per each user into %localappdata%. It never actually installs machine wide, the thing you install machine wide is just the installer that installs to each user when they sign in. 

This means that a new user logging in to the PC will get an old copy of the app installed (whatever version the msi was), and it can't even really be uninstalled properly. 

The correct way to do this is to ship an installer that properly supports installing to %programfiles% and an updater that supports prompting for elevation upon updates. I plan to implement something like this via #30 - so I'm closing this issue for now.

If you have any thoughts or specific requirements you'd like me to consider when I get around to implementing the new installer, please add them to #30 ! Thanks

**Comment by Aytharn** [comment]
I started trying this installer this morning, feels right, but as soon as I ran it in a virtual machine I was in shock, I mean I had to take back my fallen jaw when I discovered that by default it installed a Binary Executable in the roaming profile... 
out of this world.

Can you fix this insanity or at least add a --sane-destination option to vpk ?

**Comment by caesay** [comment]
@Aytharn we install nothing to roaming profile. We install to `%LocalAppData%` (not `%AppData%`). This is widely established as the correct place for per-user installs. It works the same way for thousands of other applications, including but not limited to Slack, Discord, Microsoft Teams, Chrome, Adobe, etc etc etc.

We are working on an MSI wizard installer option which will allow the user to pick whether they want it installed "per-user" (local appdata) or "per-machine" (program files). This option will not be available for the one-click installer.
