### ISSUE TITLE
Executables in package losing execute permissions after update

### ISSUE THREAD

**Issue by josh-unwin** [velopack/velopack#332]
### OS

MacOS Sonoma 14.6.1 (23G93)

### Programming Language

8.0.403

### VPK Version

0.0.869

### Library Version

?

### What happened?

As part of the C# DOTNET application files, we also bundle some third party executables inside a `libs` directory.

On MacOS, upon first installation of the program, the permissions for the executables appear to be set correctly, however when a delta update is received, the executable flag is removed.

The executables are not being changed as part of the update release.
In this example, I am demoing with [Exiftool](https://exiftool.org/).

Before update (if installed for all users):
```-rwxr-xr-x@ 1 root  wheel   319K Oct  4 10:03 exiftool```

Before update (if installed for current user only):
```-rwxr-xr-x@ 1 my_user staff   319K Oct  4 10:03 exiftool```

After update (in both installation scenarios):
```-rw-r--r--  1 my_user  staff   319K Nov  4 13:07 exiftool```

**Comment by caesay** [comment]
Velopack does not currently persist/preserve the file mode on MacOS when you run `vpk pack`, but this feature is being worked on in #63.

[The current behavior](https://github.com/velopack/velopack/blob/develop/src/lib-rust/src/bindetect.rs#L34) is to just chmod 755 anything that looks like it could be a mach-o executable. 

I gather `exiftool` is not actually a binary? Is it a shell script or similar? If you think it is a valid binary, can you please upload an example and let me know how it was compiled so I can modify the detection code?

**Comment by josh-unwin** [comment]
> Velopack does not currently persist/preserve the file mode on MacOS when you run `vpk pack`, but this feature is being worked on in #63.
> 
> [The current behavior](https://github.com/velopack/velopack/blob/develop/src/lib-rust/src/bindetect.rs#L34) is to just chmod 755 anything that looks like it could be a mach-o executable.
> 
> I gather `exiftool` is not actually a binary? Is it a shell script or similar? If you think it is a valid binary, can you please upload an example and let me know how it was compiled so I can modify the detection code?
> 
> Perhaps a workaround could be to set 755 on all the files we extract until the proper solution is available?

Thanks for the super quick response!
The exiftool package can be downloaded [here](https://exiftool.org/Image-ExifTool-13.01.tar.gz).

Apologies, you're right, the `exiftool` file is not a binary, it's a perl script.

Happy to work around by applying permissions in the meantime, would you recommend using the [App Hooks](https://docs.velopack.io/integrating/hooks) to automate that?

**Comment by caesay** [comment]
App hooks also don't work on Mac unfortunately. Also, I think modifying the file mode will require root and/or might even break your app bundle signature.

I think it might be good enough for Velopack to set all files to 755 for now, until a better solution can be implemented.
