### ISSUE TITLE
build i686-pc-windows-msvc  link error  and    x86_64-pc-windows-msvc success

### ISSUE THREAD

**Issue by guoyingbo** [velopack/velopack#333]
### OS

Windows 10

### Programming Language

C++

### VPK Version

VPK 0.0.869

### Library Version

cargo 1.82.0

### What happened?

when run : cargo build --target i686-pc-windows-msvc

get error:

 velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_run␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_args␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_auto_apply_on_startup␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_hook_after_install␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_hook_after_update␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_hook_before_uninstall␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_hook_before_update␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_hook_first_run␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_hook_restarted␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_app_set_locator␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_download_updates␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_free_asset␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_free_update_info␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_free_update_manager␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_get_app_id␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_get_current_version␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_get_last_error␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_is_portable␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_new_update_manager␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_set_log␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_update_pending_restart␍
          velopack_libc.dll.exp : error LNK2001: 无法解析的外部符号 vpkc_wait_exit_then_apply_update␍

**Comment by caesay** [comment]
The reason I don't ship a pre-compiled x86 package is that I couldn't get it to link either. If you manage to get it working, please let me know

**Comment by caesay** [comment]
Fixed in https://github.com/velopack/velopack/releases/tag/0.0.942
