### ISSUE TITLE
Missing App.exe after Setup has installed my App

### ISSUE THREAD

**Issue by farangkao** [velopack/velopack#349]
### OS

Windows 11

### Programming Language

dotnet 8

### VPK Version

vpk 0.0.594

### Library Version

0.0.594

### What happened?

Suddenly with some newly packaged apps, when installing the Setup, the <AppName>.exe in the root folder of the install location (%appdata%\<AppName>) is missing.

this causes incompatibility with existing Squirrel (for example another app tries to open this app)

I couldn't figure out the reason for this, seems there is no error ,we didnd't change configurations.

Note: it's possible the previous apps we tested, and which didn't have this behavior had a previous version of vpk/library.

Will now try to create a package with the newest version available (since we need to adjust our corresponding helper libraries as well to this version, this is a bit of hassle, therefore we didn't update always to the newest version)

**Comment by caesay** [comment]
The stub that squirrel creates in the root app dir is no longer created or needed in Velopack apps, since your actual real exe is at a stable location in the current dir.

The preferred approach is that you start your app directly from current
