### ISSUE TITLE
Support for install without default shortcuts

### ISSUE THREAD

**Issue by russell-thompson** [velopack/velopack#35]
One of our applications installs as a Windows Service. It does not have any UI requiring launch from a Desktop or Start Menu shortcut. It would be helpful to have an option to disable the creation of the default shortcuts to limit user confusion in this scenario.

**Comment by caesay** [comment]
We don't currently support windows services (eg. stopping, replacing and starting on update - elevating to admin to install, etc), but I intend to support installing windows services & configurable installers (eg. no shortcuts) via #30. I'll close this issue for now, but be sure to watch that issue and add any thoughts over there!

**Comment by Light407** [comment]
Any update on this @caesay ? I am trying to implement Velopack for a Windows Service created with UseWindowsService (Microsoft.Extensions.Hosting.WindowsServices) . Not sure if this is possible? Essentially Velopack would replace service files for an update.

This is my current code in Program.cs

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Configuration;
using Microsoft.Extensions.Logging.EventLog;
using Velopack;

VelopackApp.Build().Run();
await UpdateMyApp();

using IHost host = Host.CreateDefaultBuilder(args)
    .UseWindowsService(options =>
    {
        options.ServiceName = "My App Service";
    })
    .ConfigureServices(services =>
    {
        LoggerProviderOptions.RegisterProviderOptions<
            EventLogSettings, EventLogLoggerProvider>(services);

        services.AddHostedService<MyAppServiceManager>();
    })
    .ConfigureLogging((context, logging) =>
    {
        logging.AddConfiguration(
            context.Configuration.GetSection("Logging"));
    })
    .Build();

await host.RunAsync();


static async Task UpdateMyApp()
{
    var mgr = new UpdateManager("C:\\git\\MyAppService\\Releases");

    UpdateInfo? newVersion = null;
    try
    {
        newVersion = await mgr.CheckForUpdatesAsync();
    }
    catch { }

    try
    {
        if (newVersion == null)
            return; // no update available
    } catch { }

    // download new version
    await mgr.DownloadUpdatesAsync(newVersion);

    // install new version and restart app
    mgr.ApplyUpdatesAndRestart(newVersion);
}
```
