### ISSUE TITLE
Weird -but legal- path names not supported

### ISSUE THREAD

**Issue by parduz** [velopack/velopack#350]
### OS

Windows 11, Italian

### Programming Language

--

### VPK Version

--

### Library Version

--

### What happened?

I wrote a bug report on the [NomNom](https://github.com/zencq/NomNom) repository, [here](https://github.com/zencq/NomNom/issues/215).
They asked to open an issue here, so here i am.
I'll copy/paste my message, as i don't know nothing about the other info asked.

> 
> ### Description
> I've unpacked the zip file of the portable version and launched it. Apparently, nothing happened.
> 
> This is the content of the **Velopack.log** file:
> `
> [stub:4964] [21:47:37] [INFO] --
> [stub:4964] [21:47:37] [INFO] Starting Velopack Stub (at "F:\\- Games\\= STEAM =\\steamapps\\common\\No Man\'s Sky\\= MODS Download =\\NomNom-win-x64-stable-Portable\\NomNom.exe")
> [stub:4964] [21:47:37] [INFO] Stub about to start Update.exe (F:\- Games\= STEAM =\steamapps\common\No Man's Sky\= MODS Download =\NomNom-win-x64-stable-Portable\Update.exe) with args: ["start", "--"]
> `
> 
> I moved the **NomNom-win-x64-stable-Portable** on the F:\ root and the program started, so i'd say that he doesn't like the previous path. Since it is weird but still legal on Windows, i'd say that this is a bug.
> 
> Windows 11 64, Italian version.

### Relevant log output

```shell
[stub:4964] [21:47:37] [INFO] --
[stub:4964] [21:47:37] [INFO] Starting Velopack Stub (at "F:\\- Games\\= STEAM =\\steamapps\\common\\No Man\'s Sky\\= MODS Download =\\NomNom-win-x64-stable-Portable\\NomNom.exe")
[stub:4964] [21:47:37] [INFO] Stub about to start Update.exe (F:\- Games\= STEAM =\steamapps\common\No Man's Sky\= MODS Download =\NomNom-win-x64-stable-Portable\Update.exe) with args: ["start", "--"]
```

**Comment by caesay** [comment]
Can you provide any additional details? Seems to work fine for me with a similar path, and additionally there is no error output/message here

**Comment by parduz** [comment]
er .... what details?
I click on the app, nothing happens, the Velopack.log file got created, and it contains this:

`
[stub:16588] [10:12:22] [INFO] --
[stub:16588] [10:12:22] [INFO] Starting Velopack Stub (at "F:\\- Games\\= STEAM =\\steamapps\\common\\No Man\'s Sky\\= MODS Download =\\NomNom-win-x64-stable-Portable\\NomNom.exe")
[stub:16588] [10:12:22] [INFO] Stub about to start Update.exe (F:\- Games\= STEAM =\steamapps\common\No Man's Sky\= MODS Download =\NomNom-win-x64-stable-Portable\Update.exe) with args: ["start", "--"]
`

What should i looking for? or what else do you need to know?

**Comment by cengelha** [comment]
Hey, just a note from my side: The problem here is the `=` in the path. When executing the Velopack stub it works fine without the `=` but as soon as I put it in the folder name, the actual app does not start anymore.
I also checked with the build (that was used by Velopack to make the release) only to make sure it is not an issue with my app itself. It worked with and without `=` the path.
