### ISSUE TITLE
zsync update information for AppImages

### ISSUE THREAD

**Issue by ravener** [velopack/velopack#351]
AppImages support having update information embedded into it ([AppImage spec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information), [AppImage docs](https://docs.appimage.org/packaging-guide/optional/updates.html#making-appimages-updateable)) This utilizes [zsync](http://zsync.moria.org.uk/) to provide a meta file that can be used by downloaders such as [AppImageUpdate](https://github.com/AppImageCommunity/AppImageUpdate) this allows only downloading the files that have changed, saving time and bandwidth when updating AppImages.

Can this be done in Velopack? I come from [osu!](https://github.com/ppy/osu) where [they used to build zsync files](https://github.com/ppy/osu-deploy/blob/28da7879486a1668cf8ac91e3eaa08d5cefe82cf/Program.cs#L332) and so updates were small and simple. Since then they've migrated to Velopack and they no longer offer zsync files, so I wanted to see what could be done to return this, perhaps including a new feature in Velopack for it.

**Comment by caesay** [comment]
Velopack AppImages come with their own delta files which work differently to zsync. Therefore zsync is no longer required and I do not plan to add back support for them. The updates will still be small and simple, but sure, anything like AppImageUpdate will not be able to utilize this.

**Comment by ravener** [comment]
I see, that's pretty cool, thanks for the clarification and I apologize for my ignorance, should've read more about Velopack before posting.

Indeed it seems like osu! had also migrated to the Velopack UpdateManager, I had just never noticed it.
