### ISSUE TITLE
.NET 9 based installer tries to install .NET RC2 instead of stable release

### ISSUE THREAD

**Issue by ysmoradi** [velopack/velopack#366]
Docs

![image](https://github.com/user-attachments/assets/5317adf9-c44d-4e7e-a12c-792ec59cc97c)

Running command

![image](https://github.com/user-attachments/assets/36deafad-a4e8-4046-a370-607ca375a1ba)

First message is not talking about RC2

![image](https://github.com/user-attachments/assets/0abd8a34-50d1-4f19-bfbb-ca0a311a2099)

It downloads RC2

![image](https://github.com/user-attachments/assets/5c8942e8-ccd5-4b5e-9ba9-33b4a320a8fe)

**Comment by caesay** [comment]
The reason this happened is Microsoft themselves say RC2 is the latest version. We get the latest version via the following URL:
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/9.0/latest.version

**Comment by ysmoradi** [comment]
I just created another setup and issue still exists )":
Microsoft has solved its problem hours ago

**Comment by caesay** [comment]
I can confirm this issue has been resolved, as microsoft has fixed their release feed. If it failed for you, it was probably a cache issue for your local machine.

![image](https://github.com/user-attachments/assets/8e633897-0129-4417-b21a-9378d2603735)
![image](https://github.com/user-attachments/assets/d32e3b27-a5f9-4739-ae3f-dbd9b385c867)

**Comment by ysmoradi** [comment]
I'm unable to take screenshot of github agent vm (I can log the url's response using curl though)
But for the windows machine where setup installs
![image](https://github.com/user-attachments/assets/a3c8a7b2-4572-4c9b-8d3c-6e05500a7f2c)

**Comment by remco1271** [comment]
See that for WindowsDesktop its still '9.0.0-rc.2.24474.4'
https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/9.0/latest.version

Did report the issue see: https://github.com/dotnet/install-scripts/issues/549

**Comment by caesay** [comment]
Thanks @remco1271 for reporting that issue. Going to leave this issue closed here as there is nothing to fix.

**Comment by msynk** [comment]
> See that for WindowsDesktop its still '9.0.0-rc.2.24474.4' https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/9.0/latest.version
> 
> Did report the issue see: [dotnet/install-scripts#549](https://github.com/dotnet/install-scripts/issues/549)

Thanks for the clarification. How many of these URLs need to be updated?

**Comment by caesay** [comment]
There is one URL per SKU (windows-desktop, runtime, sdk, aspnetcore) and Microsoft updates them (usually) automatically when deploying new dotnet versions. We rely on the same infrastructure for discovering dotnet versions as dotnet's own tools.

Clearly Microsoft is having some deployment snags, which is not unexpected of new framework versions (which is why they probably shouldn't be adopted until after a few patches come out).
