### ISSUE TITLE
Generate .DirIcon for Linux AppImages

### ISSUE THREAD

**Issue by ravener** [velopack/velopack#367]
Looking at the [AppDir spec](https://docs.appimage.org/reference/appdir.html#general-description) there is a file named `.DirIcon` and can be used by thumbnailers to show an icon of the app, notably this is being used by KDE Dolphin's thumbnailer to display app icons, it is also used by tools like AppImageLauncher and at this time, AIL refuses to integrate appimages that do not contain this file

```
$ ail-cli integrate osu.AppImage.1
Processing /home/ravener/Downloads/osu.AppImage.1
Moving AppImage to integration directory
WARNING: No icons found at "usr/share/icons"
WARNING: Using .DirIcon as default app icon
ERROR: Entry doesn't exists: .DirIcon
ERROR: No icon was generated for: /home/ravener/Applications/osu.AppImage_7407d56675f47f882228974a84b820a4.1
ERROR: appimage_register_in_system : Entry doesn't exists: .DirIcon
Error: Failed to register AppImage in system via libappimage
```

since osu! had moved to Velopack a while ago, issues like https://github.com/ppy/osu/issues/30759 https://github.com/ppy/osu/discussions/30466 popped up, and after investigating, I realized the `.DirIcon` is currently missing with the Velopack setup whereas before with the AppImagetool build process it was being included, appimagetool apparently automatically picks up the root icon and creates a `.DirIcon` symlink pointing to the root icon (the one mentioned in the .desktop file)

Mounting an old appimage with `./osu.AppImage --appimage-mount` and navigating to the temp mounted directory
```
ravener@aster:/tmp/.mount_osu.ApoEzVed$ ls -a
 AppRun   .DirIcon  'osu!.desktop'  'osu!.png'   usr
ravener@aster:/tmp/.mount_osu.ApoEzVed$ file .DirIcon
.DirIcon: symbolic link to osu!.png
ravener@aster:/tmp/.mount_osu.ApoEzVed$ 
```
This was an old one built with appimagetool, but the new velopack based ones are missing this file.

[AppImageLint](https://github.com/TheAssassin/appimagelint) can also be used to check compliance:

```
./appimagelint-x86_64.AppImage --check icons_check ~/Downloads/osu.AppImage.bak                                                                         
QSocketNotifier: Can only be used with threads started with QThread
appimagelint.cli[181276] [INFO] Checking AppImage /home/ravener/Downloads/osu.AppImage.bak
appimagelint.cli[181276] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[181276] [INFO] Extracting icon name from desktop file: /tmp/.mount_osu.ApNYIqXs/osu!.desktop
appimagelint.icons_check[181276] [INFO] Checking resolution of icon: /tmp/.mount_osu.ApNYIqXs/osu!.png
appimagelint.icons_check[181276] [WARNING] icon X resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[181276] [WARNING] icon Y resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[181276] [INFO] [✔] Valid icon in AppDir root
appimagelint.icons_check[181276] [INFO] Checking resolution of icon: /tmp/.mount_osu.ApNYIqXs/.DirIcon
Traceback (most recent call last):
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/site-packages/appimagelint/__main__.py", line 4, in <module>
    run()
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/site-packages/appimagelint/cli.py", line 142, in run
    for testres in check.run():
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/site-packages/appimagelint/checks/icons.py", line 106, in run
    dotdiricon_valid = self._check_icon_for_valid_resolution(op.join(mountpoint, ".DirIcon"))
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/site-packages/appimagelint/checks/icons.py", line 279, in _check_icon_for_valid_resolution
    res = self._get_icon_res(icon_path)
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/site-packages/appimagelint/checks/icons.py", line 245, in _get_icon_res
    is_svg = self._is_svg(icon_path)
  File "/tmp/.mount_appimagGe0at/usr/conda/lib/python3.9/site-packages/appimagelint/checks/icons.py", line 222, in _is_svg
    with open(icon_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.mount_osu.ApNYIqXs/.DirIcon'
```

Here is the relevant [source code](https://github.com/AppImage/AppImageKit/blob/701b711f42250584b65a88f6427006b1d160164d/src/appimagetool.c#L825) that handles this in appimagetool

Because Velopack does not use appimagetool and builds the app image in a custom way, this will probably need to be handled here, too, to prevent incompatibilities and confusion.

**Comment by ravener** [comment]
I noticed that you are also doing [this thumbnail generation](https://github.com/velopack/velopack/blob/develop/src/vpk/Velopack.Packaging.Unix/Commands/LinuxPackCommandRunner.cs#L42)

This feels wrong and should be left up to the user's file manager to do so, KDE Dolphin for example does this, gnome doesn't by default but there are thumbnailer plugins that would. Either way they all depend on this `.DirIcon` to be present for generating a thumbnail, that's what the AppDir spec says they are for.

Imagine if pictures and videos had an executable code that thumbnailed themselves, no, it's up to the file manager to generate the preview, not our job. File managers would also do it right away instead of needing to launch the app at least once to get an icon.

**Comment by caesay** [comment]
The thumbnail generation was copied from osu! initially, the implementation here copies their original one. I agree we should add the .DirIcon but I don't see any harm in adding files to the thumbnail cache, unless you have evidence that this would break something?

**Comment by ravener** [comment]
> The thumbnail generation was copied from osu! initially, the implementation here copies their original one. I agree we should add the .DirIcon but I don't see any harm in adding files to the thumbnail cache, unless you have evidence that this would break something?

Regarding breakage, I only heard that the directory may not exist on fresh installs. but my point is less about the harm and more about the absurdity of it, this feels wrong for a default, the AppDir spec clearly specifies `.DirIcon` for this purpose:

> PNG icon located in the root directory. Can be used by e.g., thumbnailers, to display application icons rather than a generic filetype symbol. Should be in one of the standard image sizes, e.g., 128x128 or 256x256 pixels.

* I believe it's better to follow standards instead of creating tricky workarounds, no appimage ever does that. I see appimages as portable executables so they should not have side effects like that, the user can integrate them with tools like AppImageLauncher and others if they really want to install the appimage to their system in which case they get the actual menu icons and all, file manager icons are different from menu icons, linux doesn't have the concept of executable icons the way windows does so stop trying to make it like windows.
* In case of https://github.com/ppy/osu/issues/30759 it shows the user expectations, they were complaining about the missing thumbnails by their file manager, the fact that icons would get generated after launch was only an extra confusion point, that's not what users expect.
* This copy operation also happens on every launch, pointlessly adding a copy operation, even if say the file manager already thumbnailed it you'd be overriding the file every launch.

The negative aspects of it outweigh any potential benefits, since I see no benefit in that approach at all. Let file managers do their job like they do with any other files.

I don't mean to sound harsh or anything, I tried my best to explain, if anything you should ask for more community input before considering that an acceptable thing.
