### ISSUE TITLE
Failed to allow Update.exe to set foreground window

### ISSUE THREAD

**Issue by jmkinzer** [velopack/velopack#368]
### OS

Windows 11

### Programming Language

dotnet 9.0

### VPK Version

vpk 0.0.869

### Library Version

Velopack 0.0.869

### What happened?

I'm seeing "Failed to allow Update.exe to set foreground window" when updating a .net console application). Any ideas? Thanks!

### Relevant log output

```shell
warn: Platform.UpdateClient.ApplicationUpdater[0]
      Failed to allow Update.exe to set foreground window.
      System.ComponentModel.Win32Exception (5): Access is denied.
         at Velopack.UpdateExe.StartUpdateExe(ILogger logger, IVelopackLocator locator, IEnumerable`1 args)
```

**Comment by caesay** [comment]
This is just a warning that can be ignored. Presumably console applications are not allowed to set the foreground window.

**Comment by jmkinzer** [comment]
OK, such was my hope - thank you for confirming :-)
