### ISSUE TITLE
C# HttpUtil and CoreUtil inaccessible due to its protection level

### ISSUE THREAD

**Issue by cesar-albusac** [velopack/velopack#373]
### OS

Windows 11

### Programming Language

.NET Framework  4.8

### VPK Version

0.0.869

### Library Version

Nuget v0.0.869

### What happened?

I have implemented the interface IUpdateSource with a custom behaviour: 

`public class DirectoryUpdateSource : SimpleFileSource`
`public class UrlUpdateSource : SimpleWebSource`

 However, I can't use HttpUtil or CoreUtil because they are declared as internal static within the namespace Velopack.Util:
 
 `internal static class HttpUtil`
 `internal static class CoreUtil`
 
 I can't use their methods. 
 
 Within the DirectoryUpdateSource.GetReleaseFeed: 
 `var feedLoc = Path.Combine(releasesIndexDir, CoreUtil.GetVeloReleaseIndexName(channel));`
 
Within UrlUpdateSource.GetReleaseFeed:
```
var releaseFilename = CoreUtil.GetVeloReleaseIndexName(channel);
var uri = HttpUtil.AppendPathToUri(AsseFeedtUrl, releaseFilename);
```

![image](https://github.com/user-attachments/assets/b0afdf5d-ff26-42d9-9d66-4bf760d148ae)

Could those be changed to public?

**Comment by caesay** [comment]
Making API's public is unfortunately a big-ish decision. If we do it, those functions need to be documented, well supported, the API can't really change or later be removed easily eg. it will break user code.

Additionally, there's a big re-write already coming with #63 so I'm not sure if I want to make more things public now.

Those are fairly simple methods, feel free to copy them into your own code for the time being.

**Comment by cesar-albusac** [comment]
Perfect, that's what I did in the meantime, just wanted to make sure! 

Thanks for your quick response, have a nice day!
