### ISSUE TITLE
Add an argument to increase the timeout for az upload

### ISSUE THREAD

**Issue by MajesticBevans** [velopack/velopack#377]
**Is your feature request related to a problem? Please describe.**
I have slow internet, and when I try to upload the new version of my app on azure, it often fails with the following error:
``` shell
    Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The operation was cancelled because it exceeded the
    configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout
    can be adjusted in ClientOptions.Retry.NetworkTimeout.) (No such host is known. (BLOB_ACCOUNT:443)) (No such host is known. (BLOB_ACCOUNT:443))
    (No such host is known. (BLOB_ACCOUNT:443)) (No such host is known. (BLOB_ACCOUNT:443)), retrying in 1 second.
```
**Describe the solution you'd like**
I would like a command line argument that I can pass to upload az (perhaps --timeout) where I can specify a custom timeout.

**Describe alternatives you've considered**
I have looked into changing the azure cli settings, but I believe as the api is used internally in velopack, that it is not used as the timeout. Alternatively (or as well as the new custom parameter), simply increasing the timeout that velopack uses to ~5 minutes would be helpful.

**Comment by caesay** [comment]
I think the timeout we use in most upload commands is 30 minutes! so definitely needs to be fixed. Thanks for reporting.

**Comment by MajesticBevans** [comment]
That would probably do it! I'll have a crack at changing the value in a pr
