### ISSUE TITLE
CppWin32Sample.exe  Crash When Click "Download update"  button 

### ISSUE THREAD

**Issue by guoyingbo** [velopack/velopack#379]
### OS

Windows 10

### Programming Language

C++

### VPK Version

VPK 0.0.942

### Library Version

cargo 1.82.0

### What happened?

![test](https://github.com/user-attachments/assets/9f5de72a-72a2-4e43-ba10-eaa80e138608)
The response is correct when clicking "check for updates", but the program crashes when clicking "download update"。

**Comment by caesay** [comment]
We have a new cross-platform C++ sample using wxWidgets, can you try that instead?
