### ISSUE TITLE
Allow to specify exclude pattern or support a switch to include pdbs

### ISSUE THREAD

**Issue by jmkinzer** [velopack/velopack#382]
Debug assemblies appear to be excluded by default. In the vpk log I note the following message so I wonder if we could specify the exclude pattern?

Skipping because matched exclude pattern: xxx\<someassembly>.pdb

Barring that a flag to include them?

Thanks!

**Comment by caesay** [comment]
There is an `--exclude` option, which defaults to excluding pdb's. Feel free to replace the default option with something else, eg. an empty string.

**Comment by jmkinzer** [comment]
Totally missed that - thanks!
