### ISSUE TITLE
After migration from Squirrel process get stock

### ISSUE THREAD

**Issue by C1rdec** [velopack/velopack#394]
### OS

Windows

### Programming Language

dotnet 8.0 (WPF)

### VPK Version

using dotnet tool install -g vpk

### Library Version

0.942

### What happened?

The first time a user update my old Squirrel app to Velopack the new process get stock for the first launch.

I need to kill the process and start it again.

OLD Squirrel [Updatemanager](https://github.com/C1rdec/Poe-Lurker/blob/net-4.8/src/Lurker.UI/Helpers/UpdateManager.cs)

NEW Velopack [Updatemanager](https://github.com/C1rdec/Poe-Lurker/blob/main/src/PoeLurker.UI/Helpers/PoeLurkerUpdateManager.cs) 

[Velopack .Run](https://github.com/C1rdec/Poe-Lurker/blob/0fda5319fb2466e111debf85009fce396bad69db/src/PoeLurker.UI/AppBootstrapper.cs#L135C24-L135C35)

### Relevant log output

```
2024-11-30 14:20:46.7963 INFO Initializing WindowsVelopackLocator
2024-11-30 14:20:46.8049 INFO Update.exe found in parent directory
2024-11-30 14:20:46.8049 INFO Located valid manifest file at: AppData\Local\PoeLurker\current\sq.version
2024-11-30 14:20:46.8049 INFO Starting Velopack App (Run).
2024-11-30 14:20:46.8049 INFO Setting current process explicit AppUserModelID to 'velopack.PoeLurker'
```

**Comment by caesay** [comment]
Can you share your Velopack.log please

**Comment by C1rdec** [comment]
[Velopack.log](https://github.com/user-attachments/files/18017288/Velopack.log)

**Comment by caesay** [comment]
```
[update:27172] [14:20:46] [INFO] Package applied successfully.
[update:27172] [14:20:46] [INFO] Package version 2.0.0 applied successfully.
[update:27172] [14:20:46] [INFO] Removing old app-* folders...
[update:27172] [14:20:46] [INFO] About to launch: {your app path}
```

I thought you were saying the update gets stuck, but it looks like the migration from Squirrel to Velopack completed successfully. If what you're saying is, your own newly restarted app gets frozen (after the migration) I'm not sure I can help with that. The logs you've shared indicate that you've run `Velopack.Build().Run` and that has completed successfully, so there is probably a deadlock somewhere in your code which I can not see. Check for any async calls which are not .ConfigureAwait(false), and the other usual deadlock scenarios. Try attaching your debugger to see where it's stuck, etc.
