### ISSUE TITLE
Failure to apply update when the application directory is locked by another process

### ISSUE THREAD

**Issue by Arcalise08** [velopack/velopack#4]
Just a heads up here. I know its early in the project but I was a user of Squirrel.Clowd just trying out this new project. My project which worked perfectly fine with the previous squirrel is stuck in an update loop. It seems like from the logs, Its because the folder is in use.

For context, the app im porting is a ConsoleApp in .net 8. It has a specific "update" command. So powershell does have a lock on it when its being used. 

Heres some relevant logs which show the issue

```
03:35:54 [INFO] Starting Velopack Updater (0.0.82)
03:35:54 [INFO]     Location: C:\Users\MyUserAccount\AppData\Local\MyApp\Update.exe
03:35:54 [INFO]     Verbose: false
03:35:54 [INFO]     Silent: false
03:35:54 [INFO]     Log File: None
03:35:54 [INFO] Command: Apply
03:35:54 [INFO]     Restart: true
03:35:54 [INFO]     Wait: true
03:35:54 [INFO]     Package: None
03:35:54 [INFO]     Exe Args: Some(["update"])
03:35:54 [INFO]     No Elevate: false
03:35:54 [INFO] Loaded manifest for application: MyApp
03:35:54 [INFO] Root Directory: C:\Users\MyUserAccount\AppData\Local\MyApp
03:35:54 [INFO] Reading parent process information.
03:35:54 [INFO] Waiting 60000ms for parent process (115776) to exit.
03:35:54 [WARN] Failed to wait for parent process to exit (Failed to wait for parent process to exit.).
03:35:54 [INFO] Attempting to open global system mutex: 'velopack-MyApp'
03:35:54 [INFO] No package specified, searching for latest.
03:35:55 [INFO] Found 1.0.0: 'C:\Users\MyUserAccount\AppData\Local\MyApp\packages\MyApp-1.0.0-full.nupkg'
03:35:55 [INFO] Found 1.0.1: 'C:\Users\MyUserAccount\AppData\Local\MyApp\packages\MyApp-1.0.1-win-full.nupkg'
03:35:55 [INFO] Checking application pre-requisites...
03:35:55 [INFO] Applying package to current: 1.0.1
03:35:55 [INFO] Running --veloapp-obsolete hook...
03:35:55 [INFO] Hook executed successfully (took 92.24911ms)
03:35:55 [INFO] Checking for running processes in: C:\Users\MyUserAccount\AppData\Local\MyApp
03:35:55 [WARN] Killing process: C:\Users\MyUserAccount\AppData\Local\MyApp\current\MyApp.exe (115776)
03:35:55 [WARN] Skipping killing self: C:\Users\MyUserAccount\AppData\Local\MyApp\Update.exe (110652)
03:35:55 [INFO] Renaming directory 'C:\Users\MyUserAccount\AppData\Local\MyApp\current' to 'C:\Users\MyUserAccount\AppData\Local\MyApp\current_jlgn8Qtx' to allow rollback...
03:35:55 [INFO] Checking for running processes in: C:\Users\MyUserAccount\AppData\Local\MyApp\current
03:35:55 [WARN] Retrying operation in 333ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:35:55 [WARN] Retrying operation in 666ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:35:56 [WARN] Retrying operation in 1000ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:35:57 [WARN] Last retry in 1000ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:35:58 [ERROR] Failed to apply package: Failed to rename directory 'C:\Users\MyUserAccount\AppData\Local\MyApp\current' to 'C:\Users\MyUserAccount\AppData\Local\MyApp\current_jlgn8Qtx' (The process cannot access the file because it is being used by another process. (os error 32)).
03:35:58 [INFO] Will try to elevate permissions and try again...
03:36:00 [INFO] Attempting to elevate: C:\Users\MyUserAccount\AppData\Local\MyApp\Update.exe ["apply", "--noelevate", "--restart", "--", "update"]
03:36:02 [INFO] Starting Velopack Updater (0.0.82)
03:36:02 [INFO]     Location: C:\Users\MyUserAccount\AppData\Local\MyApp\Update.exe
03:36:02 [INFO]     Verbose: false
03:36:02 [INFO]     Silent: false
03:36:02 [INFO]     Log File: None
03:36:02 [INFO] Command: Apply
03:36:02 [INFO]     Restart: true
03:36:02 [INFO]     Wait: false
03:36:02 [INFO]     Package: None
03:36:02 [INFO]     Exe Args: Some(["update"])
03:36:02 [INFO]     No Elevate: true
03:36:02 [INFO] Loaded manifest for application: MyApp
03:36:02 [INFO] Root Directory: C:\Users\MyUserAccount\AppData\Local\MyApp
03:36:02 [INFO] Attempting to open global system mutex: 'velopack-MyApp'
03:36:02 [INFO] No package specified, searching for latest.
03:36:02 [INFO] Found 1.0.0: 'C:\Users\MyUserAccount\AppData\Local\MyApp\packages\MyApp-1.0.0-full.nupkg'
03:36:02 [INFO] Found 1.0.1: 'C:\Users\MyUserAccount\AppData\Local\MyApp\packages\MyApp-1.0.1-win-full.nupkg'
03:36:02 [INFO] Checking application pre-requisites...
03:36:02 [INFO] Applying package to current: 1.0.1
03:36:02 [INFO] Running --veloapp-obsolete hook...
03:36:02 [INFO] Hook executed successfully (took 98.5044ms)
03:36:02 [INFO] Checking for running processes in: C:\Users\MyUserAccount\AppData\Local\MyApp
03:36:02 [WARN] Skipping killing self: C:\Users\MyUserAccount\AppData\Local\MyApp\Update.exe (107936)
03:36:02 [INFO] Renaming directory 'C:\Users\MyUserAccount\AppData\Local\MyApp\current' to 'C:\Users\MyUserAccount\AppData\Local\MyApp\current_PioLOhTH' to allow rollback...
03:36:02 [INFO] Checking for running processes in: C:\Users\MyUserAccount\AppData\Local\MyApp\current
03:36:02 [WARN] Retrying operation in 333ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:36:02 [WARN] Retrying operation in 666ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:36:03 [WARN] Retrying operation in 1000ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:36:04 [WARN] Last retry in 1000ms... (error was: Some(Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }))
03:36:05 [ERROR] Failed to apply package: Failed to rename directory 'C:\Users\MyUserAccount\AppData\Local\MyApp\current' to 'C:\Users\MyUserAccount\AppData\Local\MyApp\current_PioLOhTH' (The process cannot access the file because it is being used by another process. (os error 32)).
03:36:05 [ERROR] Error applying package: Failed to rename directory 'C:\Users\MyUserAccount\AppData\Local\MyApp\current' to 'C:\Users\MyUserAccount\AppData\Local\MyApp\current_PioLOhTH' (The process cannot access the file because it is being used by another process. (os error 32)).
03:36:05 [INFO] Verifying authenticode signatures of prospective launch binary...
03:36:05 [INFO] About to launch: 'C:\Users\MyUserAccount\AppData\Local\MyApp\current\MyApp.exe' in dir 'C:\Users\MyUserAccount\AppData\Local\MyApp\current'
03:36:05 [INFO] Args: CommandArgs { inner: [Regular("update")] }
```

**Comment by caesay** [comment]
Indeed, probably the CWD of your shell or of powershell is inside the current directory, so it can't be re-named. How would you like to see this resolved by Velopack ideally?

**Comment by Arcalise08** [comment]
> Indeed, probably the CWD of your shell or of powershell is inside the current directory, so it can't be re-named. How would you like to see this resolved by Velopack ideally?

Ideally in this situation it would prompt that resources are in use and tell the user to either close them or attempt to automatically close them with a prompt.

**Comment by caesay** [comment]
It wouldn't be possible to close them automatically probably. There are not any processes in the directory that are running, and even if we did try to enumerate every running process on your machine, and check the CWD of that process, it is slow and prone to breaking. 

We could show a dialog. What would you like to see in that dialog? Just a generic error message saying there is something using the application directory and to try again later?

**Comment by Arcalise08** [comment]
``> It wouldn't be possible to close them automatically probably. There are not any processes in the directory that are running, and even if we did try to enumerate every running process on your machine, and check the CWD of that process, it is slow and prone to breaking.
> 
> We could show a dialog. What would you like to see in that dialog? Just a generic error message saying there is something using the application directory and to try again later?

I mean, I do disagree a bit with that conclusion. Actively running processes should be checked by any type of auto-updater tech. It doesnt have to go in depth with it. Just a simple attempt to identify and kill would be fine
```
static Process? GetLockingProcess(string filePath)
    {
        var processes = Process.GetProcesses();
        foreach (var process in processes)
        {
            try
            {
                if (process.Modules.Cast<ProcessModule>().Any(m => string.Equals(m.FileName, filePath, StringComparison.InvariantCultureIgnoreCase)))
                {
                    return process;
                }
            }
            catch
            {
            }
        }
        return null;
    }

var p = GetLockingProcess(someFile);
if (p is not null)
 p.Kill();
```

Its not a hill I'd die on or anything. Just something thats nice, especially for applications which tend to run a lot in parallel.  I'd look at something like Visual Studios dialog for this, Its pretty nice.

![image](https://github.com/velopack/velopack/assets/61042848/5323c40b-9cc2-43d8-9432-963298b84f7d)

Thats a super clean way to do it but also not super trivial to do. Something more trivial would be like, a try catch around the file handler exception which just prompts a dialog with

> Update Interrupted
> 
> Oops! It looks like one or more files needed for the update are currently in use.
> 
> To proceed with the update, please close any programs that might be using these files and click "Retry".
> 
> If you're unsure which programs to close, a system restart might help.
> 
> [Retry] [Cancel]

**Comment by caesay** [comment]
Velopack already checks for running processes inside your application directory and kills them automatically. You can see this happening in the logs you shared. What's happening for you (I think) is that either cmd.exe or powershell.exe (which do not reside in your application directory) have locked your directory because their current working dir (CWD) is currently inside that directory. 

Checking the CWD of running processes is a lot harder to do, I mean - just look at some of the answers to these questions: https://stackoverflow.com/questions/14018280/how-to-get-a-process-working-dir-on-windows or https://stackoverflow.com/questions/2967650/is-it-possible-to-determine-the-working-directory-of-another-process

I would happily show a dialog like the VSIX installer, but I suspect that is only doing the really trivial/naive thing (checking running processes by location) that we already do.

**Comment by Arcalise08** [comment]
Gotcha. I assumed this was just because it wasnt checking if the app was running at all. Sorry for the issue bloat here. 

I'm unsure if this is actually something even needed anymore if it does the trivial checking. My use case is, a console app which i used velopack to package. It was only in the initial development i ran into this issue because i hadn't yet made the script which would add my app to the users PATH. so i had to navigate in powershell to the install location. 

My users wouldnt do this. I'm not sure anyone would. So its probably not worth the time to do.
