### ISSUE TITLE
Unable to verify VelopackApp when VelopackApp.Build() wrapped in another method

### ISSUE THREAD

**Issue by Basyras** [velopack/velopack#40]
Hey, after migrating from clowd.squirrel to velopack I was calling `SquirrelAwareApp.HandleEvents` not directly in main method - it was wrapped in another method. When updating to velopack I endup with this code:
```
    public static int Main(string[] args)
    {
        Log.Information("Starting up!");

        try
        {
            CreateAndRunHostBuilder(args);
            return 0;
        }
        catch (Exception ex)
        {
            return 1;
        }
    }

    private static void CreateAndRunHostBuilder(string[] args)
    {
        var hostBuilder = OfficeHost.CreateDefaultBuilder(args);
        VelopackApp.Build()
            .WithFirstRun(VelopackEventHandlers.OnAppInstall)
            .Run();

        var host = hostBuilder.ConfigureServices(x =>
            {
               //Registering services
            })
            .Build();

        host.Run();
    }
```
But this throws `Unable to verify VelopackApp` exception when trying `vpk pack`.
Its not big deal for me as I can just move the code but I can imagine in future lot of people will complain about this.
I was looking in the source code how the check is done and yeah Iam not sure if this is the "perfect" path to check (but seems better then the previous marking the project with SquirreAware app attribute.)

I you have any idea how we could improve that I am willing help.

**Comment by caesay** [comment]
I'm certainly open to suggestions on how to improve this. The check is mainly there to catch people out who have forgotten to add `VelopackApp` somewhere to their startup. If you forget to add this some really weird things happen, and it's no longer an optional step - your app **must** start with this code.

In your case, if you want to keep the code as-is, you can just disable the check with `--skipVeloAppCheck`

**Comment by Basyras** [comment]
Oh that is what `--skipVeloAppCheck` is for.

Yeah I agree adding this check (exception) is handy.
I see it is the hidden option in vpk. I am not sure why did you decide to hide it but I would prob. keep it visible by default. But perhaps what would be the most beneficial is that if the error message thrown in `DotnetUtil.VerifyVelopackApp` could mention this cli option. Felt like this option is not even mentioned anywhere in docs?

**Comment by DrEsteban** [comment]
Agree. This should be mentioned in the docs somewhere.
