### ISSUE TITLE
Separately Update Multiple Flies

### ISSUE THREAD

**Issue by TimTheBig** [velopack/velopack#409]
### Description
Add functionality to update multiple flies separately.
Say I had two binarys, one was a launcher and the other is the main programme, since the launcher works on any version it doesn't need to be updated as often. This is when having multiple flies with their own sources is useful.

### Solution
Add a system that allows for multiple flies with their own sources.

**Comment by caesay** [comment]
Velopack is not going to allow you to update specific files, but you can already do what you are asking by treating your launcher and main app as "separate apps". All Velopack apps are (can be) portable, so if you want those nested into the same install dir you can arrange that. 

Using the Locator, you can even update/manage other apps, so I know people have developed "app portal" type launchers, which download/install/update other applications. 

If you have questions about how to accomplish any of this feel free to ask in our discord
