### ISSUE TITLE
Preserve S3 header file headers when updating releases.json

### ISSUE THREAD

**Issue by b0bben** [velopack/velopack#45]
**Background:**
We're exposing our installer/updater hosted on S3 thru CloudFront for caching/edge-node purposes. Since Velopack updates the release-xxx.json files with new version info we need to set some headers in S3 so CloudFront knows when the file is updated and thus start serving new version of file(s).
Right now the `vpk upload s3` command will overwrite the files with empty headers.

**Proposed solution:**
https://github.com/velopack/velopack/blob/8b74e0fc74b55f2c315595215a8f83f77e6120d7/src/Velopack.Deployment/S3Repository.cs#L157
Existing code (above) already reads the metadata of the existing S3 file, that metadata should contain the existing headers, and can thus be re-added in PutObjectRequest, something like:
`var req = new PutObjectRequest {
            BucketName = bucket,
            FilePath = f.FullName,
            Key = key,
            Headers = metadata.Headers,
        };`

**Comment by caesay** [comment]
Just a thought - would it not be preferrable if vpk just set the appropriate cache policy out of the box on new uploads rather than preserving headers you need to set manually? What headers specifically do you need to set on the files for this to work correctly with CloudFront?

**Comment by b0bben** [comment]
> Just a thought - would it not be preferrable if vpk just set the appropriate cache policy out of the box on new uploads rather than preserving headers you need to set manually? What headers specifically do you need to set on the files for this to work correctly with CloudFront?

That's even better! I think `Cache-Control: must-revalidate` is enough.

**Comment by caesay** [comment]
Developed in 685b4b674447a76dc2ea51853a9eaee8b2d3d380
