### ISSUE TITLE
Configure one-click installer shortcut locations

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#46]
It's been a requested feature which I have denied adding for a while, but I will implement this as a hidden command line option during packing (eg. `--shortcuts Desktop,StartMenuRoot`).

**Comment by Pyritie** [comment]
will the command line option just enable those shortcuts or how will it work for disabling them?

**Comment by caesay** [comment]
When this is released, `--shortcuts {locations...}` will configure the installer and uninstaller for where you would like shortcuts to be automatically created/deleted.

**Comment by shunkica** [comment]
Is it possible (as of current release) to have the Start Menu shortcut created in `Start Menu/Author/PackTitle`instead of `Start Menu/PackTitle` ?
Quickdoc says `Shortcuts()` is obsolete, and `CreateShortcutForThisExe` only allows creation of shortcut in root of Desktop and Start Menu.
