### ISSUE TITLE
Deltas for trivial updates

### ISSUE THREAD

**Issue by jackmang** [velopack/velopack#48]
I am excited by this project.  A possible great opportunity to move on from ClickOnce.  Squirrel seems dead, but from the ashes you seem to have created something pretty exciting.  Thanks for your efforts and may I also compliment you on the documentation & marketing site that you've put together.  Looks great!

Anyway...

I created an absolute minimal WinForms application with .Net 8 to test using Velopack.  I followed the instructions to build a first version and then installed it using the created setup exe file.  No problems.  I then make a super-trivial change, rebuild and republish.  I look to the Releases folder to confirm that the full update is 92MB and the delta is 190KB.  All looks good at this point.  

For reference these are the build commands (based on your docs):
dotnet publish -c Release --self-contained -r win-x64
vpk pack -u YourAppId -v 1.0.13 -p .\bin\Release\net8.0-windows\win-x64\publish -e VelopackTest.exe --packTitle "Velopack Test Application"

When I run the installed application and call for an update, the update works, but the log file AppData\Local\MyAppID\Velopack.log appears to show both a patch and full update.

I see it appearing to patch VelopackTest.dll, but I also see it later referencing YourAppId-1.0.13-full.nupkg and stating that it is extracting 472 files.  Am I just misinterpreting the log data?

14:59:00 [INFO] Starting Velopack Updater (0.0.349)
14:59:00 [INFO]     Location: C:\Users\XXXXXXX\AppData\Local\YourAppId\Update.exe
14:59:00 [INFO]     Verbose: false
14:59:00 [INFO]     Silent: false
14:59:00 [INFO]     Log File: None
14:59:00 [INFO] Command: Patch
14:59:00 [INFO]     Old File: "C:\\Users\\XXXXXXX\\AppData\\Local\\YourAppId\\packages\\VelopackTemp\\temp.1\\lib\\app\\sq.version"
14:59:00 [INFO]     Patch File: "C:\\Users\\XXXXXXX\\AppData\\Local\\YourAppId\\packages\\VelopackTemp\\temp.2\\lib\\app\\sq.version.zsdiff"
14:59:00 [INFO]     Output File: "C:\\Users\\XXXXXXX\\AppData\\Local\\YourAppId\\packages\\VelopackTemp\\temp.3"
14:59:00 [INFO] Loading Dictionary (Size: 407)
14:59:00 [INFO] Decoder loaded. Beginning patch...
14:59:00 [INFO] Patch applied successfully.
14:59:00 [INFO] Starting Velopack Updater (0.0.349)
14:59:00 [INFO]     Location: C:\Users\XXXXXXX\AppData\Local\YourAppId\Update.exe
14:59:00 [INFO]     Verbose: false
14:59:00 [INFO]     Silent: false
14:59:00 [INFO]     Log File: None
14:59:00 [INFO] Command: Patch
14:59:00 [INFO]     Old File: "C:\\Users\\XXXXXXX\\AppData\\Local\\YourAppId\\packages\\VelopackTemp\\temp.1\\lib\\app\\VelopackTest.dll"
14:59:00 [INFO]     Patch File: "C:\\Users\\XXXXXXX\\AppData\\Local\\YourAppId\\packages\\VelopackTemp\\temp.2\\lib\\app\\VelopackTest.dll.zsdiff"
14:59:00 [INFO]     Output File: "C:\\Users\\XXXXXXX\\AppData\\Local\\YourAppId\\packages\\VelopackTemp\\temp.3"
14:59:00 [INFO] Loading Dictionary (Size: 7680)
14:59:00 [INFO] Decoder loaded. Beginning patch...
14:59:00 [INFO] Patch applied successfully.
14:59:06 [INFO] Starting Velopack Updater (0.0.349)
14:59:06 [INFO]     Location: C:\Users\XXXXXXX\AppData\Local\YourAppId\Update.exe
14:59:06 [INFO]     Verbose: false
14:59:06 [INFO]     Silent: false
14:59:06 [INFO]     Log File: None
14:59:06 [INFO] Command: Apply
14:59:06 [INFO]     Restart: true
14:59:06 [INFO]     Wait: false
14:59:06 [INFO]     Wait PID: Some(14200)
14:59:06 [INFO]     Package: Some("C:\\Users\\XXXXXXX\\AppData\\Local\\YourAppId\\packages\\YourAppId-1.0.13-full.nupkg")
14:59:06 [INFO]     Exe Args: None
14:59:06 [INFO] Loaded manifest for application: YourAppId
14:59:06 [INFO] Root Directory: C:\Users\XXXXXXX\AppData\Local\YourAppId
14:59:06 [INFO] Attempting to open global system mutex: 'velopack-YourAppId'
14:59:06 [INFO] Waiting 60000ms for process (14200) to exit.
14:59:06 [INFO] Getting ready to apply package to YourAppId ver 1.0.12: C:\Users\XXXXXXX\AppData\Local\YourAppId\packages\YourAppId-1.0.13-full.nupkg
14:59:06 [INFO] Applying package to current: 1.0.13
14:59:06 [INFO] Checking application pre-requisites...
14:59:06 [INFO] Running --veloapp-obsolete hook...
14:59:06 [INFO] Hook executed successfully (took 118.2532ms)
14:59:06 [INFO] Checking for running processes in: C:\Users\XXXXXXX\AppData\Local\YourAppId
14:59:06 [WARN] Skipping killing self: C:\Users\XXXXXXX\AppData\Local\YourAppId\Update.exe (21768)
14:59:06 [INFO] Extracting bundle to C:\Users\XXXXXXX\AppData\Local\YourAppId\packages\tmp_RxGV3BPn
14:59:06 [INFO] Extracting 472 app files...
14:59:09 [INFO] Checking for running processes in: C:\Users\XXXXXXX\AppData\Local\YourAppId
14:59:09 [WARN] Skipping killing self: C:\Users\XXXXXXX\AppData\Local\YourAppId\Update.exe (21768)
14:59:09 [INFO] Replacing bundle at C:\Users\XXXXXXX\AppData\Local\YourAppId\current
14:59:09 [INFO] Bundle extracted successfully to C:\Users\XXXXXXX\AppData\Local\YourAppId\current
14:59:09 [INFO] Writing uninstall registry key...
14:59:09 [INFO] Running --veloapp-updated hook...
14:59:11 [INFO] Hook executed successfully (took 1556.3842ms)
14:59:11 [INFO] Checking for running processes in: C:\Users\XXXXXXX\AppData\Local\YourAppId
14:59:11 [WARN] Skipping killing self: C:\Users\XXXXXXX\AppData\Local\YourAppId\Update.exe (21768)
14:59:11 [INFO] Package applied successfully.
14:59:11 [INFO] Package version 1.0.13 applied successfully.
14:59:11 [INFO] About to launch: 'C:\Users\XXXXXXX\AppData\Local\YourAppId\current\VelopackTest.exe' in dir 'C:\Users\XXXXXXX\AppData\Local\YourAppId\current'
14:59:11 [INFO] Args: CommandArgs { inner: [] }

If needed, please let me know what additional information I could supply and I'll do my best to supply it.

**Comment by caesay** [comment]
This is all working as expected. The C# NuGet package downloads the delta's, and reconstructs a `-full` package locally on disk. The Update.exe then replaces your whole app (`current` folder) with the new reconstructed version. You're not getting the whole picture here because you're not including the logs from `UpdateManager`. Please provide an `ILogger to `VelopackApp` or to `UpdateManager` to see the rest of the logs, and there you'll see the delta's being downloaded and reconstructed.
