### ISSUE TITLE
A way to use a dynamic UpdateUrl ?

### ISSUE THREAD

**Issue by quacrobat** [velopack/velopack#51]
Hi,
Is there a way to avoid hard-coding UpdateUrl in Porgram.cs, to avoid having to toggle (and sometimes forget) changing it say from localhost to the live server?

Would it be possible to have the option of it always falling back to wherever Url the latest update was downloaded from?

**Comment by caesay** [comment]
Hi there, you don't need to specify the UpdateUrl in Program.cs of course, you can store it anywhere, config variables etc. We are working on something which will allow you to skip providing an UpdateUrl entirely, but I'm not ready to release more information about it yet. Check back in a month or two!
