### ISSUE TITLE
Package ID restrictions/limitations?

### ISSUE THREAD

**Issue by JonathanS-NTI** [velopack/velopack#53]
In Squirrel.Windows/Clowd.Squirrel, using [periods in the package ID](https://github.com/clowd/Clowd.Squirrel/blob/2.11.1/docs/using/naming.md#local-install-location) was not supported (I think).  [This test](https://github.com/velopack/velopack/blob/f364e480748068980dcf894c464e68cc9a1d425e/test/Velopack.CommandLine.Tests/Commands/WindowsCommandTests.cs#L301) seems to indicate any valid [Nuget package ID](https://learn.microsoft.com/en-us/nuget/reference/nuspec#id) will work.  The tests in this file also imply that periods are supported.  What are the restrictions or limitations for package ID with Velopack?

**Comment by caesay** [comment]
Hi there, the logic is here: https://github.com/velopack/velopack/blob/f364e480748068980dcf894c464e68cc9a1d425e/src/Velopack/NuGet/NugetUtil.cs#L39

So it's any "word" characters, dashes, and dots.
