### ISSUE TITLE
Release notes of Velopack itself?

### ISSUE THREAD

**Issue by Dunge** [velopack/velopack#54]
I'm not talking about embedding release notes in our apps updates, but I would like to see what's new when a new package of Velopack get released on nuget.org (both the Velopack lib and the vpk tool).

There's no release note on the documentation site, no release tab in github, no release section in the readme...

Otherwise I switched my app to use this tool for our deployment and I'm very happy with it so far, so thanks a lot for the efforts!

**Comment by caesay** [comment]
Hi there, we're still in pre-release/beta mode (denoted by the `0.0.*` version number). This means we're making changes fairly rapidly and there's lots of stuff that can still change before we release `v1`! - but it's coming soon. I think we should be out with v1 within the next month or two, and from then on we will stick to semantic-versioning and provide the typical release notes via GitHub releases. Thanks for trying Velopack!
