### ISSUE TITLE
Support uploading to Azure Storage 

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#56]

**Comment by bhorn** [comment]
PR #58 created, borrowing heavily from the S3 code.

**Comment by absinghal** [comment]
Under this issue, will there be support for Azure container Sas with write permissions ?

Thanks

**Comment by caesay** [comment]
Thanks @bhorn - this was commited into develop branch via bfb834b5da935591fbc2648c325d2dc91bc18ec2, d098cc5a7f1969b855c7069c51842ba298202a06 and 5aaa8f61c46f1d7c7545947aecb28809f0414e4b. I have added support for authenticating via `--sas` token instead of a secret key. This will be released as a pre-release soon.

**Comment by caesay** [comment]
0.0.431-g5aaa8f6
