### ISSUE TITLE
0.0.359  HelperFile could not find 'stup.exe'

### ISSUE THREAD

**Issue by Huochengyan** [velopack/velopack#66]
Hello I use the vpk command packaging prompt can not find stup.exe, look at the dotnet tool installation directory did not
![image](https://github.com/velopack/velopack/assets/24469860/d915660f-db0a-47c3-bb4f-4e1829c8c9fe)

**Comment by Huochengyan** [comment]
After trying to copy the dotnet tool under the setup.exe renamed stup.exe can be

**Comment by caesay** [comment]
The command line shows as vpk version `0.0.0`, it doesn't look right. How did you install vpk?

**Comment by caesay** [comment]
What was your issue? How did you resolve it?
