### ISSUE TITLE
Shortcuts not updated when `--packTitle` or application icon changes

### ISSUE THREAD

**Issue by LiamDHall** [velopack/velopack#67]
Icon and shortcut name not updated when channel is swapped. The shortcut will continue to show the --packTitle and icon of the original version installed.

**Comment by caesay** [comment]
The icon comes from your application executable automatically, I suspect if you restart your computer the icon will be updated. It's true that we don't update shortcuts automatically at any point, only install them in Setup.exe and remove them during uninstall.

**Comment by LiamDHall** [comment]
I have tried restarting and sadly it hasn't updated. If it something manual I need to do on channel swap I don't mind. Is the code for the shortcut creation in the repo and I'll adapt it to my needs?

**Comment by caesay** [comment]
https://docs.velopack.io/integrating/shortcuts

**Comment by LiamDHall** [comment]
Ah easy, cheers for the helps.
