### ISSUE TITLE
Virus detected in Microsoft edge

### ISSUE THREAD

**Issue by tgiachi** [velopack/velopack#71]
Hi, I'm trying to download my own file setup from S3 (where is hosted) by Edge blocking me with this error:

![image](https://github.com/velopack/velopack/assets/942730/6f366e04-f424-416a-922b-666bccf87bae)

in detail:

![image](https://github.com/velopack/velopack/assets/942730/848a6900-51c2-4841-a86b-c1dc4dd856fc)

how I can whitelist my setup ?

Thank you
Tommaso

**Comment by caesay** [comment]
Make sure your app is code signed (https://docs.velopack.io/packaging/signing) and submit your app to Microsoft for malware analysis before publishing https://www.microsoft.com/en-us/wdsi/filesubmission
