### ISSUE TITLE
AWS deployment should use default credential lookup if user and password are not provided

### ISSUE THREAD

**Issue by bzuillsmith** [velopack/velopack#72]
These lines appear to always expect a user and key and do not fall back to default profile credentials (or other credential types) https://github.com/velopack/velopack/blob/develop/src/Velopack.Deployment/S3Repository.cs#L84-L86

When using the AWS SDK, you can instantiate services with the default constructor and the SDK will look for credentials in various other locations (.aws folder, environment variables etc). This is the preferred method for providing the SDK with credentials according to their docs. It would also make ci/cd work more easily in services like AWS CodeBuild which automatically set up service roles and credentials profiles on the build instances. The current constructor unfortunately does not fall back to these default credentials and so, it appears I have to make a user and key for my ci/cd pipeline.

**Comment by caesay** [comment]
Fixed in d5f709ddf356fad6aae9fa7a85329c425866774a, deployed in 0.0.462-gf8acc97
