### ISSUE TITLE
assets.CHANNELNAME.json should use relative paths

### ISSUE THREAD

**Issue by AArnott** [velopack/velopack#82]
To cater to #18 not being an option, I'm building my velopack packages on the build agents that match the target OS.
But I'm not _uploading_ those packages from multiple machines, because I only want to publish a release across channels if the whole pipeline succeeded.

So what I've crafted is to build the packages first, on various build agents, and collect these packages as pipeline artifacts.
Then I have a final job that (if everything else was successful) downloads the pipeline artifacts created by the 3 build agents and then uploads all the velopack packages at once.

The problem I run into is that the `assets.CHANNELNAME.json` file contains absolute paths rather than relative paths. And the absolute path has changed from one agent to the next. So `vpk upload` fails.

Can we get `vpk pack` to create this assets json file with relative paths, and `vpk upload` to accept that?

**Comment by caesay** [comment]
Agreed, this needs to get looked at. Ideally I'd like to deprecate assets.{channel}.json entirely, it's only used by the upload command. I feel like the intended behavior is probably always to just take and upload the latest releases for the specified channel. That's easy for `.nupkg` files, we just open it and read the embedded channel. Not so easy for installers. We can guess based on the filename but I don't love that.

As a workaround for now, you could write a small script on your final uploading agent

**Comment by AArnott** [comment]
> As a workaround for now, you could write a small script on your final uploading agent which writes a new assets file.

Yes, that's exactly what I have in mind.

Thanks for reviewing.

**Comment by caesay** [comment]
This is now done
