### ISSUE TITLE
Shortcut class (un)deprecation

### ISSUE THREAD

**Issue by Pyritie** [velopack/velopack#89]
While I understand that the typical use case will want desktop/start menu shortcuts, please don't enforce creating shortcuts for all installed apps. I used squirrel (and am now migrating to velopack) to install tools that are ran by other apps (such as perforce) that users should never run by themselves, and so they should never be on the user's desktop/start menu.

At the moment I am using the Shortcuts class to delete the shortcuts as soon as velopack creates them, with an ugly `#pragma warning disable CS0618` around that block to stop the obsolete warnings.

**Comment by Trinitek** [comment]
There's an open suggestion at #46 that would allow us to configure the shortcut locations during `vpk pack`.

**Comment by Pyritie** [comment]
That would be great, but when you say hidden, does that mean it won't be on your documentation? If so, why not?

**Comment by caesay** [comment]
I won't be un-deprecating the `Shortcuts` class, I don't plan to remove it either because there are some legitimate use-cases, but in general #46 will be the way forward here as well as #30
