### ISSUE TITLE
Microsoft Visual C++ 2015-2019 Redistributable dependency

### ISSUE THREAD

**Issue by ysmoradi** [velopack/velopack#9]
Which of [vcredist supported by velopack](https://github.com/velopack/velopack/blob/master/docs/bootstrapping.md#vcredist) is equivalent to: https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net80#additional-deps
![Screenshot_20240121_005724_Edge](https://github.com/velopack/velopack/assets/5352980/6318a14e-d31b-41ae-b985-53d429ff26f8)
What value should be supplied to --framework?

**Comment by caesay** [comment]
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
It follows the standard VC++ versioning. 
vcredist100 is for 10.0 (2010)
vcredist110 is for 11.0 (2012)
12.0 is 2013
14.0 is 2015
14.1 is 2017
14.2 is 2019
14.3 is 2022

If you install any of the 14.* versions, and it's missing, the latest (14.3) will be installed. Based on that screenshot I'd assume you could depend on install 142 and be fine.
