### ISSUE TITLE
When upgrading from Squirrel.Windows to Velopack, do not recreate shortcuts if the user had previously deleted them

### ISSUE THREAD

**Issue by Trinitek** [velopack/velopack#94]
When applying updates, Squirrel.Windows expressly did not attempt to recreate desktop or Start menu shortcuts if the user had previously deleted them. When Squirrel.Windows applies a Velopack package and begins the migration process, Velopack should match this behavior and not recreate the shortcuts as if it were a fresh installation.

**Comment by caesay** [comment]
I'm don't think I can fix this. Velopack doesn't know what shortcuts were configured to be installed in Squirrel. Imagine that your Squirrel install only added a StartMenuRoot - but now in Velopack you would like to have shortcuts in Desktop as well. We can't tell the difference between "squirrel installed desktop shortcut but user deleted" and "there was never a desktop shortcut".
