### ISSUE TITLE
Problem with custom shortcuts

### ISSUE THREAD

**Issue by Nils-Berghs** [velopack/velopack#95]
This is not really related to #46 but it's also about shortcuts.

For my application, I need two shortcuts to the same executable in the same location (e.g. desktop or start menu). On is just the standard  shortcut that is auto created. The second one should pass a parameter to the application to start it in a different mode

The problem is that the 'Name' for the shortcut can not be specified in create shortcut, so while I can create the second shortcut with the parameter, it will override the default shortcut.

**Comment by caesay** [comment]
Hi there, you're able to create shortcuts however you'd like - using the [VelopackApp.Build().WithAfterInstallFastCallback](https://docs.velopack.io/reference/cs/Velopack/VelopackApp#withafterinstallfastcallbackvelopackhook) hook. There is a `Shortcuts` class for some basic out of the box functionality, but if you need anything beyond that please refer to the [ShellLink](https://docs.velopack.io/reference/cs/Velopack.Windows/ShellLink) class which provides the capability to create a shortcut anywhere with any title / icon etc.
