### ISSUE TITLE
Packing fails with space in mainExe

### ISSUE THREAD

**Issue by remco1271** [velopack/velopack#96]
Packing fails when there is a space in the main EXE.

Powershell:
```
vpk pack `
    --packId "Bus_Monitor" `
    --packTitle "Bus monitor" `
    --outputDir "Z:\Build\Releases\" `
    --icon ".\Icons\ico\CAN.ico" `
    --packVersion 1.0.0 `
    --packDir ".\PublishBuild" `
    --mainExe "Bus Monitor.exe" `
    --splashImage ".\splash.gif" `
    --framework net6.0-x86-desktop
```
Output:
```
vpk : Unrecognized command or argument 'Monitor.exe --splashImage .\splash.gif --framework net6.0-x86-desktop'.
At C:\Users\Remco\source\repos\Bus-Monitor\PublishBuild.ps1:60 char:1
+ vpk pack
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unrecognized co...0-x86-desktop'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by caesay** [comment]
This seems to work fine for me using v0.0.359. I used powershell as well just to test:

![image](https://github.com/velopack/velopack/assets/1287295/3dd978b2-0bfe-49a3-97f1-e1f97151baa2)

I think it might be an issue with your command line string, your dotnet environment, or your powershell environment. I'd ask you to please test this using cmd.exe and simplifying the command arguments to identify the cause.

**Comment by remco1271** [comment]
Did some more tests and your command did work without problem.
Found that changing the command `--outputDir "Z:\Build\Releases\" ` to `--outputDir ".\Releases\` did solve the problem.

**Comment by remco1271** [comment]
Here more information what I get out of PowerShell directly without running a script with output dis as Z.
You can see that the options after the _outputDir_ are there but aren't found.
```
PS C:\Users\Remco\source\repos\can-wpf> vpk pack --packId "Bus_Monitor" --packTitle "Bus monitor" --outputDir "Z:\build\Releases\" --icon ".\Icons\ico\CAN.ico" --packVersion 1.0.0 --packDir ".\PublishBuild" --mainExe "Bus Monitor.exe" --splashImage ".\splash.gif" --framework net6.0-x86-desktop

Unrecognized command or argument 'Monitor.exe --splashImage .\splash.gif --framework net6.0-x86-desktop'.
Option '--packVersion' is required.
Option '--packDir' is required.
```

**Comment by caesay** [comment]
I see you've closed the issue, what was your solution?

**Comment by remco1271** [comment]
Changing the output dir from a network drive to a relative path as you see above.
All arguments after the outputDir will not be read from args if I use the network drive
