### ISSUE TITLE
ApplyUpdatesAndRestart modifies restartArgs before passing them along.

### ISSUE THREAD

**Issue by Noah1989** [velopack/velopack#99]
I noticed that when I add an argument like "Foo=Bar" to the `restartArgs` array, it actually gets passed along as two separate arguments "Foo" and "Bar". This is surprising, but I guess there is some nomalizaton going on (I couln't find where in the code that is, though). It would be preferable to leave everything afer "--" as-is.

**Comment by caesay** [comment]
It's probably [this line here](https://github.com/velopack/velopack/blob/develop/src/Rust/src/update.rs#L69), which only exists for legacy Squirrel support. The squirrel command line was something like `--processStartAndWait=myProcess.exe` which is still supported but gets converted into `--processStart myProcess.exe --wait` which then gets converted into `start --wait myProcess`. 

I agree though, this is not ideal. We should ignore everything after `--` when doing this processing.

**Comment by caesay** [comment]
Fixed in b1cc241ed9557e5e262cc22d9669a5db67ab0044
